/**
 * Fee Engine API Client
 * 
 * Masraf/harç hesaplaması için TEK KAYNAK.
 * UI'da masraf hesabı YASAK - bu client kullanılmalı.
 * 
 * @see ARCHITECTURE.md - Source of Truth Matrix
 * @see fee-engine/fee-engine.service.ts
 */

import { apiClient } from './client';

// ============================================
// TYPES
// ============================================

export interface FeeComputeRequest {
  caseId: string;
  caseType: string;
  principalAmount: number;
  debtorCount: number;
  calculationDate?: string;
}

export interface GeneratedFeeItem {
  code: string;
  name: string;
  amount: number;
  currency: string;
  description?: string;
  isAutoGenerated: boolean;
  tariffCode?: string;
}

export interface FeeComputeResult {
  caseId: string;
  items: GeneratedFeeItem[];
  totals: {
    basvurmaHarci: number;
    vekaletHarci: number;
    pesinHarc: number;
    dosyaGideri: number;
    tebligatGideri: number;
    vekaletPulu: number;
    toplam: number;
  };
  currency: string;
  calculatedAt: string;
}

export interface AttorneyFeeRequest {
  amount: number;
  currency?: string;
}

export interface AttorneyFeeResult {
  amount: number;
  currency: string;
  breakdown?: {
    bracket: string;
    rate: number;
    amount: number;
  }[];
  minimumFee: number;
  calculatedFee: number;
  finalFee: number;
}

export interface TariffInfo {
  year: number;
  effectiveDate: string;
  items: {
    code: string;
    name: string;
    rate?: number;
    fixedAmount?: number;
    minAmount?: number;
  }[];
}

// ============================================
// PREVIEW TYPES (Lightweight, no audit)
// ============================================

export interface FeePreviewRequest {
  principalAmount: number;
  caseType?: string;
  debtorCount?: number;
}

export interface FeePreviewResponse {
  success: boolean;
  data?: {
    estimatedFees: number;
    estimatedAttorneyFee: number;
    tariffYear: number;
    breakdown: {
      basvurmaHarci: number;
      vekaletHarci: number;
      pesinHarc: number;
      dosyaGideri: number;
      tebligatGideri: number;
      vekaletPulu: number;
    };
  };
  error?: {
    code: 'INVALID_INPUT' | 'SERVICE_UNAVAILABLE';
    message: string;
  };
  cached: boolean;
  cacheExpiry?: string;
}

// ============================================
// API CLIENT
// ============================================

export const feeEngineApi = {
  /**
   * Preview fee calculation (lightweight, no audit)
   * 
   * Frontend form preview için kullanılır.
   * API erişilemezse { success: false } döner - TAHMİN YAPILMAZ.
   * 
   * @see docs/single-source-of-truth-architecture.md
   */
  preview: async (request: FeePreviewRequest): Promise<FeePreviewResponse> => {
    try {
      const response = await apiClient.post('/fee-engine/preview', request);
      return response.data;
    } catch (error) {
      console.error('[feeEngineApi.preview] Error:', error);
      return {
        success: false,
        error: {
          code: 'SERVICE_UNAVAILABLE',
          message: 'Masraf hesaplama servisi şu an erişilemiyor',
        },
        cached: false,
      };
    }
  },

  /**
   * Masraf/harç hesapla
   * 
   * @example
   * const result = await feeEngineApi.compute({
   *   caseId: 'abc-123',
   *   caseType: 'CHECK',
   *   principalAmount: 100000,
   *   debtorCount: 2,
   * });
   */
  compute: async (request: FeeComputeRequest): Promise<FeeComputeResult> => {
    const response = await apiClient.post('/fee-engine/compute', request);
    return response.data;
  },

  /**
   * Vekalet ücreti hesapla
   * 
   * @example
   * const result = await feeEngineApi.getAttorneyFee({ amount: 100000 });
   */
  getAttorneyFee: async (request: AttorneyFeeRequest): Promise<AttorneyFeeResult> => {
    const response = await apiClient.post('/fee-engine/attorney-fee', request);
    return response.data;
  },

  /**
   * Peşin harç hesapla
   */
  getPesinHarc: async (principalAmount: number): Promise<{ amount: number; rate: number }> => {
    const response = await apiClient.post('/fee-engine/pesin-harc', { principalAmount });
    return response.data;
  },

  /**
   * Tahsil harcı hesapla
   */
  getTahsilHarci: async (amount: number, includePesinHarc: boolean = false): Promise<{ amount: number; rate: number }> => {
    const response = await apiClient.post('/fee-engine/tahsil-harci', { amount, includePesinHarc });
    return response.data;
  },

  /**
   * Güncel tarife bilgisini al
   */
  getCurrentTariff: async (): Promise<TariffInfo> => {
    const response = await apiClient.get('/fee-engine/tariff/current');
    return response.data;
  },

  /**
   * Belirli yılın tarifesini al
   */
  getTariffByYear: async (year: number): Promise<TariffInfo> => {
    const response = await apiClient.get(`/fee-engine/tariff/${year}`);
    return response.data;
  },
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Para formatla (display için)
 */
export function formatFee(amount: number, currency: string = 'TRY'): string {
  return new Intl.NumberFormat('tr-TR', {
    style: 'currency',
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}
