import { Injectable, OnModuleInit, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

// ============================================
// TİPLER
// ============================================

export interface TariffFixedFee {
  amount: number;
  label: string;
  item_type: string;
  applies_to: string[];
}

export interface TariffRateFee {
  rate: number;
  label: string;
  item_type: string;
  base: string;
  applies_to: string[];
  min_amount?: number;
  max_amount?: number;
}

export interface TariffPostage {
  amount: number | null;
  label: string;
  description: string;
  formula?: string;
}

export interface TariffInterestRate {
  start_date: string;
  rate: number;
}

export interface Tariff {
  version: number;
  year: number;
  effective_date: string;
  fixed_fees: Record<string, TariffFixedFee>;
  rate_fees: Record<string, TariffRateFee>;
  postage: Record<string, TariffPostage>;
  interest_rates: Record<string, Record<string, TariffInterestRate[]>>;
  penalties: Record<string, any>;
}

export interface FeeProfileItem {
  code: string;
  item_type: string;
  label: string;
  auto_add: boolean;
  formula?: {
    base: string;
    rate_from_tariff: string;
  };
}

export interface FeeProfile {
  applies_to_case_types: string[];
  tariff_year: number;
  fixed_fee_items: FeeProfileItem[];
  rate_fee_items: FeeProfileItem[];
  postage_policy: {
    default: string;
    allow: string[];
    auto_add: boolean;
    per_debtor?: boolean;
  };
}

export interface GeneratedFeeItem {
  type: string;
  label: string;
  amount: number;
  currency: string;
  description?: string;
  isAutoGenerated: boolean;
  tariffCode?: string;
}

// ============================================
// FEE ENGINE SERVİSİ
// ============================================

@Injectable()
export class FeeEngineService implements OnModuleInit {
  private readonly logger = new Logger(FeeEngineService.name);
  private tariffs: Map<number, Tariff> = new Map();
  private feeProfiles: Map<string, FeeProfile> = new Map();
  private currentYear: number = new Date().getFullYear();

  async onModuleInit() {
    await this.loadTariffs();
    await this.loadFeeProfiles();
  }

  // ============================================
  // YAML YÜKLEME
  // ============================================

  private async loadTariffs(): Promise<void> {
    try {
      const possiblePaths = [
        path.join(process.cwd(), 'src/config/tariffs'),
        path.join(process.cwd(), 'dist/config/tariffs'),
        path.join(__dirname, '../../config/tariffs'),
      ];

      for (const basePath of possiblePaths) {
        if (fs.existsSync(basePath)) {
          const files = fs.readdirSync(basePath).filter(f => f.endsWith('.yaml'));
          for (const file of files) {
            const year = parseInt(file.replace('.yaml', ''));
            if (!isNaN(year)) {
              const content = fs.readFileSync(path.join(basePath, file), 'utf8');
              const tariff = yaml.load(content) as Tariff;
              this.tariffs.set(year, tariff);
              this.logger.log(`✅ Tarife yüklendi: ${year}`);
            }
          }
          break;
        }
      }

      if (this.tariffs.size === 0) {
        this.logger.warn('Tarife dosyası bulunamadı, varsayılan değerler kullanılacak');
        this.tariffs.set(2025, this.getDefaultTariff());
      }
    } catch (error) {
      this.logger.error('Tarife yüklenemedi:', error);
      this.tariffs.set(2025, this.getDefaultTariff());
    }
  }

  private async loadFeeProfiles(): Promise<void> {
    try {
      const possiblePaths = [
        path.join(process.cwd(), 'src/config/fee-profiles.yaml'),
        path.join(process.cwd(), 'dist/config/fee-profiles.yaml'),
        path.join(__dirname, '../../config/fee-profiles.yaml'),
      ];

      for (const configPath of possiblePaths) {
        if (fs.existsSync(configPath)) {
          const content = fs.readFileSync(configPath, 'utf8');
          const data = yaml.load(content) as any;
          
          // Her profili map'e ekle
          for (const [key, profile] of Object.entries(data)) {
            if (key !== 'version' && key !== 'engine') {
              this.feeProfiles.set(key, profile as FeeProfile);
            }
          }
          
          this.logger.log(`✅ ${this.feeProfiles.size} masraf profili yüklendi`);
          break;
        }
      }

      if (this.feeProfiles.size === 0) {
        this.logger.warn('Masraf profili bulunamadı, varsayılan değerler kullanılacak');
        this.loadDefaultFeeProfiles();
      }
    } catch (error) {
      this.logger.error('Masraf profilleri yüklenemedi:', error);
      this.loadDefaultFeeProfiles();
    }
  }

  // ============================================
  // VARSAYILAN DEĞERLER
  // ============================================

  private getDefaultTariff(): Tariff {
    return {
      version: 1,
      year: 2025,
      effective_date: '2025-01-01',
      fixed_fees: {
        application_fee: { amount: 615.40, label: 'Başvurma Harcı', item_type: 'FEE', applies_to: ['ILAMSIZ', 'ILAMLI', 'KAMBIYO'] },
        poa_copy_fee: { amount: 87.50, label: 'Vekalet Suret Harcı', item_type: 'FEE', applies_to: ['ILAMSIZ', 'ILAMLI', 'KAMBIYO'] },
        bar_stamp_fee: { amount: 138.00, label: 'Vekalet Pulu', item_type: 'STAMP', applies_to: ['ILAMSIZ', 'ILAMLI', 'KAMBIYO'] },
      },
      rate_fees: {
        ilamsiz_pesin_harc: { rate: 0.005, label: 'Peşin Harç', item_type: 'FEE', base: 'principal_plus_interest', applies_to: ['ILAMSIZ', 'KIRA'], min_amount: 100 },
        kambiyo_pesin_harc: { rate: 0.005, label: 'Peşin Harç', item_type: 'FEE', base: 'principal_plus_interest', applies_to: ['KAMBIYO'], min_amount: 100 },
      },
      postage: {
        UETS: { amount: 15.00, label: 'UETS Tebligat', description: 'Elektronik tebligat' },
        NORMAL: { amount: 210.00, label: 'Normal Tebligat', description: 'PTT normal tebligat' },
        FAST: { amount: 420.00, label: 'Hızlı Tebligat', description: 'PTT hızlı tebligat' },
        PUBLIC_ANNOUNCEMENT: { amount: null, label: 'İlanen Tebligat', description: 'Gazete ilanı' },
      },
      interest_rates: {
        TRY: {
          YASAL: [{ start_date: '2024-01-01', rate: 24 }],
          TICARI: [{ start_date: '2024-01-01', rate: 48 }],
        },
      },
      penalties: {
        bad_check_compensation: { default_rate: 0.10, max_rate: 0.20 },
      },
    };
  }

  private loadDefaultFeeProfiles(): void {
    this.feeProfiles.set('ILAMSIZ_OPENING', {
      applies_to_case_types: ['ILAMSIZ', 'KIRA', 'TAHLIYE'],
      tariff_year: 2025,
      fixed_fee_items: [
        { code: 'application_fee', item_type: 'FEE', label: 'Başvurma Harcı', auto_add: true },
        { code: 'poa_copy_fee', item_type: 'FEE', label: 'Vekalet Suret Harcı', auto_add: true },
        { code: 'bar_stamp_fee', item_type: 'STAMP', label: 'Vekalet Pulu', auto_add: true },
      ],
      rate_fee_items: [
        { code: 'ilamsiz_pesin_harc', item_type: 'FEE', label: 'Peşin Harç', auto_add: true, formula: { base: 'principal_plus_interest', rate_from_tariff: 'ilamsiz_pesin_harc' } },
      ],
      postage_policy: { default: 'NORMAL', allow: ['UETS', 'NORMAL', 'FAST'], auto_add: true, per_debtor: true },
    });

    this.feeProfiles.set('KAMBIYO_OPENING', {
      applies_to_case_types: ['KAMBIYO'],
      tariff_year: 2025,
      fixed_fee_items: [
        { code: 'application_fee', item_type: 'FEE', label: 'Başvurma Harcı', auto_add: true },
        { code: 'poa_copy_fee', item_type: 'FEE', label: 'Vekalet Suret Harcı', auto_add: true },
        { code: 'bar_stamp_fee', item_type: 'STAMP', label: 'Vekalet Pulu', auto_add: true },
      ],
      rate_fee_items: [
        { code: 'kambiyo_pesin_harc', item_type: 'FEE', label: 'Peşin Harç', auto_add: true, formula: { base: 'principal_plus_interest', rate_from_tariff: 'kambiyo_pesin_harc' } },
      ],
      postage_policy: { default: 'NORMAL', allow: ['UETS', 'NORMAL', 'FAST'], auto_add: true, per_debtor: true },
    });

    this.feeProfiles.set('ILAMLI_OPENING', {
      applies_to_case_types: ['ILAMLI'],
      tariff_year: 2025,
      fixed_fee_items: [
        { code: 'application_fee', item_type: 'FEE', label: 'Başvurma Harcı', auto_add: true },
        { code: 'poa_copy_fee', item_type: 'FEE', label: 'Vekalet Suret Harcı', auto_add: true },
        { code: 'bar_stamp_fee', item_type: 'STAMP', label: 'Vekalet Pulu', auto_add: true },
      ],
      rate_fee_items: [],
      postage_policy: { default: 'UETS', allow: ['UETS', 'NORMAL', 'FAST'], auto_add: true, per_debtor: true },
    });
  }

  // ============================================
  // ANA FONKSİYONLAR
  // ============================================

  /**
   * Takip türüne göre açılış masraflarını hesapla
   */
  calculateOpeningFees(
    caseType: string,
    principalAmount: number,
    accruedInterest: number = 0,
    debtorCount: number = 1,
    postageType: string = 'NORMAL',
    tariffYear?: number,
  ): GeneratedFeeItem[] {
    const year = tariffYear || this.currentYear;
    const tariff = this.tariffs.get(year) || this.tariffs.get(2025)!;
    const items: GeneratedFeeItem[] = [];

    // Uygun profili bul
    const profile = this.findProfileForCaseType(caseType);
    if (!profile) {
      this.logger.warn(`Masraf profili bulunamadı: ${caseType}`);
      return items;
    }

    // 1. Sabit harçlar
    for (const feeItem of profile.fixed_fee_items) {
      if (!feeItem.auto_add) continue;
      
      const tariffFee = tariff.fixed_fees[feeItem.code];
      if (tariffFee && tariffFee.applies_to.includes(caseType)) {
        items.push({
          type: feeItem.item_type,
          label: feeItem.label,
          amount: tariffFee.amount,
          currency: 'TRY',
          isAutoGenerated: true,
          tariffCode: feeItem.code,
        });
      }
    }

    // 2. Nispi harçlar
    for (const feeItem of profile.rate_fee_items) {
      if (!feeItem.auto_add) continue;
      
      const tariffFee = tariff.rate_fees[feeItem.code];
      if (tariffFee && tariffFee.applies_to.includes(caseType)) {
        const base = principalAmount + accruedInterest;
        let amount = base * tariffFee.rate;
        
        // Min/max kontrol
        if (tariffFee.min_amount && amount < tariffFee.min_amount) {
          amount = tariffFee.min_amount;
        }
        if (tariffFee.max_amount && amount > tariffFee.max_amount) {
          amount = tariffFee.max_amount;
        }
        
        items.push({
          type: feeItem.item_type,
          label: feeItem.label,
          amount: Math.round(amount * 100) / 100,
          currency: 'TRY',
          description: `%${(tariffFee.rate * 100).toFixed(2)} oranında`,
          isAutoGenerated: true,
          tariffCode: feeItem.code,
        });
      }
    }

    // 3. Tebligat gideri
    if (profile.postage_policy.auto_add) {
      const postage = tariff.postage[postageType] || tariff.postage[profile.postage_policy.default];
      if (postage && postage.amount) {
        const count = profile.postage_policy.per_debtor ? debtorCount : 1;
        items.push({
          type: 'POSTAGE',
          label: postage.label,
          amount: postage.amount * count,
          currency: 'TRY',
          description: count > 1 ? `${count} borçlu için` : undefined,
          isAutoGenerated: true,
          tariffCode: postageType,
        });
      }
    }

    return items;
  }

  /**
   * Takip türüne göre profil bul
   */
  private findProfileForCaseType(caseType: string): FeeProfile | null {
    for (const [, profile] of this.feeProfiles) {
      if (profile.applies_to_case_types.includes(caseType)) {
        return profile;
      }
    }
    return null;
  }

  /**
   * Faiz oranını getir
   */
  getInterestRate(
    currency: string,
    interestType: string,
    date?: Date,
    tariffYear?: number,
  ): number {
    const year = tariffYear || this.currentYear;
    const tariff = this.tariffs.get(year) || this.tariffs.get(2025)!;
    
    const currencyRates = tariff.interest_rates[currency];
    if (!currencyRates) return 24; // Varsayılan yasal faiz
    
    const typeRates = currencyRates[interestType];
    if (!typeRates || typeRates.length === 0) return 24;
    
    const dateStr = (date || new Date()).toISOString().split('T')[0];
    let applicableRate = typeRates[0].rate;
    
    for (const entry of typeRates) {
      if (entry.start_date <= dateStr) {
        applicableRate = entry.rate;
      }
    }
    
    return applicableRate;
  }

  /**
   * Tebligat ücretini getir
   */
  getPostageAmount(postageType: string, tariffYear?: number): number {
    const year = tariffYear || this.currentYear;
    const tariff = this.tariffs.get(year) || this.tariffs.get(2025)!;
    
    const postage = tariff.postage[postageType];
    return postage?.amount || 0;
  }

  /**
   * Ceza/tazminat hesapla
   */
  calculatePenalty(
    penaltyType: string,
    principalAmount: number,
    customRate?: number,
    tariffYear?: number,
  ): number {
    const year = tariffYear || this.currentYear;
    const tariff = this.tariffs.get(year) || this.tariffs.get(2025)!;
    
    const penalty = tariff.penalties[penaltyType];
    if (!penalty) return 0;
    
    const rate = customRate ?? penalty.default_rate;
    const effectiveRate = penalty.max_rate ? Math.min(rate, penalty.max_rate) : rate;
    
    return Math.round(principalAmount * effectiveRate * 100) / 100;
  }

  /**
   * Mevcut tarife yılını getir
   */
  getCurrentTariffYear(): number {
    return this.currentYear;
  }

  /**
   * Tüm tebligat türlerini getir
   */
  getPostageTypes(tariffYear?: number): Array<{ code: string; label: string; amount: number | null }> {
    const year = tariffYear || this.currentYear;
    const tariff = this.tariffs.get(year) || this.tariffs.get(2025)!;
    
    return Object.entries(tariff.postage).map(([code, data]) => ({
      code,
      label: data.label,
      amount: data.amount,
    }));
  }

  /**
   * Profil için izin verilen tebligat türlerini getir
   */
  getAllowedPostageTypes(caseType: string): string[] {
    const profile = this.findProfileForCaseType(caseType);
    return profile?.postage_policy.allow || ['NORMAL'];
  }

  /**
   * Toplam masraf hesapla
   */
  calculateTotalFees(items: GeneratedFeeItem[]): number {
    return items.reduce((sum, item) => sum + item.amount, 0);
  }
}
