/**
 * Alerting Data Models
 * 
 * Production Alerting System - Sprint 0
 * 
 * Data models for signals, alerts, incidents, and payloads.
 * 
 * @see .kiro/specs/production-alerting-system/requirements.md
 * @see .kiro/specs/production-alerting-system/design.md
 */

import {
  AlertCategory,
  AlertSeverity,
  AlertStatus,
  AlertType,
  AnomalySeverity,
  GlobalOutageReason,
  IncidentStatus,
  NotificationChannel,
  OwnerTeam,
  ResolutionReason,
  ResourceType,
  SignalCollectorType,
  SuppressionReason,
  TenantScope,
} from '../types/alerting.types';

// ============================================================================
// RAW SIGNALS (from collectors)
// ============================================================================

/**
 * Base raw signal from collectors
 */
export interface RawSignal {
  /** Signal ID (generated by collector) */
  signalId: string;
  /** Timestamp (ISO 8601) */
  timestamp: string;
  /** Source component */
  component: string;
  /** Tenant ID (optional for global signals) */
  tenantId?: string;
  /** Collector type */
  collectorType: SignalCollectorType;
}

/**
 * Security signal from SecurityCollector
 * 
 * @see Requirements 3.1-3.5
 */
export interface SecuritySignal extends RawSignal {
  collectorType: SignalCollectorType.Security;
  signalType: 'JTI_ANOMALY' | 'CROSS_TENANT_ATTEMPT' | 'CROSS_TENANT_BLOCKED';
  anomalyType?: 'HIGH_USAGE' | 'MULTI_ACTOR';
  severity: AnomalySeverity;
  jti?: string;
  grantId?: string;
  actorCount?: number;
  targetTenantId?: string;
}

/**
 * Health signal from HealthCollector
 * 
 * @see Requirements 1.1-1.5, 2.1-2.4
 */
export interface HealthSignal extends RawSignal {
  collectorType: SignalCollectorType.Health;
  signalType: 'DEGRADED_ENTERED' | 'DEGRADED_EXITED' | 'FAILURE_RECORDED' | 'MANUAL_RESET_REQUIRED';
  degradedDurationMs?: number;
  consecutiveFailures?: number;
  manualResetRequired?: boolean;
}

/**
 * Capacity signal from CapacityCollector
 * 
 * @see Requirements 5.1-5.6
 */
export interface CapacitySignal extends RawSignal {
  collectorType: SignalCollectorType.Capacity;
  signalType: 'RATE_LIMIT_EXHAUSTED' | 'QUEUE_DEPTH_HIGH' | 'RESOURCE_HIGH';
  resourceType?: ResourceType;
  currentValue: number;
  threshold: number;
  limitKey?: string;
  queueName?: string;
}

/**
 * Integrity signal from IntegrityCollector
 * 
 * @see Requirements 6.1-6.3
 */
export interface IntegritySignal extends RawSignal {
  collectorType: SignalCollectorType.Integrity;
  signalType: 'AUDIT_WRITE_FAILURE' | 'STATUS_MISMATCH';
  expectedState?: string;
  actualState?: string;
  errorMessage?: string;
}

/**
 * Hygiene signal from HygieneCollector
 * 
 * @see Requirements 7.1-7.2
 */
export interface HygieneSignal extends RawSignal {
  collectorType: SignalCollectorType.Hygiene;
  signalType: 'VALIDATION_ERROR_SPIKE';
  errorType: string;
  errorCount: number;
  windowMs: number;
  threshold: number;
}

/**
 * Union of all raw signal types
 */
export type AnyRawSignal =
  | SecuritySignal
  | HealthSignal
  | CapacitySignal
  | IntegritySignal
  | HygieneSignal;

// ============================================================================
// NORMALIZED SIGNAL
// ============================================================================

/**
 * Normalized signal - common format for all signals
 * 
 * @see Requirements 15.1-15.7
 */
export interface NormalizedSignal {
  /** Unique signal ID */
  signalId: string;
  /** Signal timestamp (ISO 8601) */
  timestamp: string;
  /** Source component */
  component: string;
  /** Tenant ID (optional - global signals have no tenant) */
  tenantId?: string;
  /** Signal type */
  signalType: string;
  /** Signal category */
  category: AlertCategory;
  /** Dimensions for alertKey generation */
  dimensions: Record<string, string | number>;
  /** Raw severity hint from collector */
  rawSeverityHint?: AlertSeverity;
  /** Evidence reference (audit trail pointer) */
  evidenceRef?: string;
  /** Original raw signal */
  rawSignal: AnyRawSignal;
}

// ============================================================================
// ALERT
// ============================================================================

/**
 * Alert model
 * 
 * @see Requirements 15.1-15.7
 */
export interface Alert {
  /** Unique alert ID */
  alertId: string;
  /** Alert type */
  alertType: AlertType;
  /** Alert category */
  category: AlertCategory;
  /** Alert severity */
  severity: AlertSeverity;
  /** Owner team */
  ownerTeam: OwnerTeam;
  /** Tenant scope */
  tenantScope: TenantScope;
  /** Tenant ID (single_tenant ise) */
  tenantId?: string;
  /** Alert key (dedupe key) */
  alertKey: string;
  /** Correlation ID */
  correlationId: string;
  /** Incident ID */
  incidentId: string;
  /** Recommendation */
  recommendation: string;
  /** Runbook reference */
  runbookRef: string;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
  /** Resolved timestamp */
  resolvedAt?: string;
  /** Alert status */
  status: AlertStatus;
  /** Maintenance context */
  maintenanceContext?: boolean;
  /** Suppression context */
  suppressionContext?: SuppressionContext;
  /** Related incident IDs */
  relatedIncidentIds: string[];
}

/**
 * Suppression context for suppressed alerts
 */
export interface SuppressionContext {
  suppressedBy: string;
  parentIncidentId: string;
  reason: SuppressionReason;
}

// ============================================================================
// ALERT PAYLOAD (for notification)
// ============================================================================

/**
 * Alert payload for notification service
 * 
 * @see Requirements 15.1-15.7
 */
export interface AlertPayload {
  /** Unique alert ID */
  alertId: string;
  /** Incident ID */
  incidentId: string;
  /** Alert type */
  alertType: AlertType;
  /** Alert category */
  category: AlertCategory;
  /** Alert severity */
  severity: AlertSeverity;
  /** Owner team */
  ownerTeam: OwnerTeam;
  /** Tenant scope */
  tenantScope: TenantScope;
  /** Tenant ID (single_tenant ise) */
  tenantId?: string;
  /** Alert key (dedupe key) */
  alertKey: string;
  /** Correlation ID */
  correlationId: string;
  /** Related incident IDs */
  relatedIncidentIds: string[];
  /** Recommendation */
  recommendation: string;
  /** Runbook link */
  runbookLink: string;
  /** Created timestamp */
  createdAt: string;
  /** Source component */
  component: string;
  /** Maintenance context */
  maintenanceContext?: boolean;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// INCIDENT
// ============================================================================

/**
 * Incident model
 * 
 * Represents a deduplicated alert instance.
 */
export interface Incident {
  /** Unique incident ID */
  incidentId: string;
  /** Alert key (dedupe key) */
  alertKey: string;
  /** Correlation ID */
  correlationId: string;
  /** Alert type */
  alertType: AlertType;
  /** Alert category */
  category: AlertCategory;
  /** Alert severity */
  severity: AlertSeverity;
  /** Tenant scope */
  tenantScope: TenantScope;
  /** Tenant ID (single_tenant ise) */
  tenantId?: string;
  /** Incident status */
  status: IncidentStatus;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
  /** Resolved timestamp */
  resolvedAt?: string;
  /** Resolution details */
  resolution?: IncidentResolution;
  /** Aggregated alert count */
  alertCount: number;
  /** Last alert timestamp */
  lastAlertAt: string;
  /** Source component */
  component: string;
}

/**
 * Incident resolution details
 * 
 * @see Requirements 8.1-8.3
 */
export interface IncidentResolution {
  /** Resolution reason */
  reason: ResolutionReason;
  /** Root cause hint */
  rootCauseHint?: string;
  /** Resolved by (actor ID) */
  resolvedBy?: string;
  /** Duration in milliseconds */
  durationMs: number;
}

// ============================================================================
// GLOBAL OUTAGE
// ============================================================================

/**
 * Global outage model
 * 
 * @see Requirements 17.4
 */
export interface GlobalOutage {
  /** Unique outage ID */
  outageId: string;
  /** Outage reason */
  reason: GlobalOutageReason;
  /** Affected categories */
  affectedCategories: AlertCategory[];
  /** Started timestamp */
  startedAt: string;
  /** Resolved timestamp */
  resolvedAt?: string;
  /** Outage status */
  status: 'ACTIVE' | 'RESOLVED';
  /** Source incident ID (if escalated from incident) */
  sourceIncidentId?: string;
  /** Declared by (actor ID) */
  declaredBy?: string;
}

// ============================================================================
// SUPPRESSION
// ============================================================================

/**
 * Suppression result
 * 
 * @see Requirements 17.1-17.5
 */
export interface SuppressionResult {
  /** Should suppress */
  suppressed: boolean;
  /** Suppression reason */
  reason?: SuppressionReason;
  /** Severity clamped */
  severityClamped?: boolean;
  /** Clamped severity */
  clampedSeverity?: AlertSeverity;
  /** Maintenance context */
  maintenanceContext?: boolean;
  /** Parent alert ID (inhibit durumunda) */
  suppressedBy?: string;
}

// ============================================================================
// FLAPPING
// ============================================================================

/**
 * Flapping result
 * 
 * @see Requirements 9.1-9.5
 */
export interface FlappingResult {
  /** Flapping detected */
  isFlapping: boolean;
  /** Flap count (last 60 minutes) */
  flapCount: number;
  /** Suggested severity */
  suggestedSeverity?: AlertSeverity;
  /** Trigger RCA */
  triggerRca: boolean;
  /** Recommendation */
  recommendation?: string;
}

// ============================================================================
// TREND
// ============================================================================

/**
 * Trend analysis result
 * 
 * @see Requirements 18.1-18.6
 */
export interface TrendResult {
  /** Trend detected */
  hasTrend: boolean;
  /** Failure rate (0-1) */
  failureRate: number;
  /** Slope (positive = increasing, negative = decreasing) */
  slope: number;
  /** Sample count */
  sampleCount: number;
  /** Statistically significant */
  statisticallySignificant: boolean;
  /** Window start timestamp */
  windowStart: string;
  /** Window end timestamp */
  windowEnd: string;
}

/**
 * Burn rate result
 * 
 * @see Requirements 18.4
 */
export interface BurnRateResult {
  /** Burn rate (errorRate / allowedErrorRate) */
  burnRate: number;
  /** SLO target */
  sloTarget: number;
  /** Current value */
  currentValue: number;
  /** Remaining budget (%) */
  remainingBudget: number;
}

// ============================================================================
// NOTIFICATION
// ============================================================================

/**
 * Notification request
 */
export interface NotificationRequest {
  /** Idempotency key (duplicate prevention) */
  idempotencyKey: string;
  /** Alert payload */
  alert: AlertPayload;
  /** Target channels */
  channels: NotificationChannel[];
  /** Priority (affects retry behavior) */
  priority: 'high' | 'normal' | 'low';
}

/**
 * Notification result
 */
export interface NotificationResult {
  /** Notification ID */
  notificationId: string;
  /** Overall success */
  success: boolean;
  /** Per-channel results */
  channelResults: ChannelResult[];
  /** Retry scheduled */
  retryScheduled: boolean;
  /** Next retry time (if scheduled) */
  nextRetryAt?: string;
}

/**
 * Channel result
 */
export interface ChannelResult {
  channel: NotificationChannel;
  success: boolean;
  error?: string;
  deliveredAt?: string;
  attemptCount: number;
}

/**
 * Dead letter entry
 */
export interface DeadLetterEntry {
  entryId: string;
  notification: NotificationRequest;
  failureReason: string;
  failedAt: string;
  attemptCount: number;
  lastAttemptAt: string;
}

// ============================================================================
// ROUTING
// ============================================================================

/**
 * Routing result
 */
export interface RoutingResult {
  /** Owner team */
  ownerTeam: OwnerTeam;
  /** Escalation policy */
  escalationPolicy: string;
  /** Notification channels */
  channels: NotificationChannel[];
}

// ============================================================================
// DEDUPE
// ============================================================================

/**
 * Dedupe result
 */
export interface DedupeResult {
  /** Should dedupe */
  deduplicated: boolean;
  /** Dedupe reason */
  reason?: 'same_alert_window' | 'cooldown_active' | 'flapping_aggregation';
  /** Existing alert ID (if deduplicated) */
  existingAlertId?: string;
  /** Existing incident ID (if deduplicated) */
  existingIncidentId?: string;
}

// ============================================================================
// INHIBIT
// ============================================================================

/**
 * Inhibit result
 */
export interface InhibitResult {
  /** Should inhibit */
  inhibit: boolean;
  /** Parent outage ID */
  parentOutageId?: string;
  /** Inhibit reason */
  reason?: string;
}
