/**
 * Phase 5.6 - Tariff Provider Contract Tests
 * 
 * Schema + Semantic validation tests.
 * 
 * @see contracts/README.md
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  FeeItemSchema,
  FeeCalculationResultSchema,
  FeePreviewResponseSchema,
  validateFeeItem as validateFeeItemSchema,
  validateFeeCalculationResult as validateFeeCalcSchema,
  validateFeePreviewResponse as validatePreviewSchema,
  TARIFF_PROVIDER_SCHEMA_VERSION,
} from './schema';
import {
  validateFeeItem as validateFeeItemSemantic,
  validateFeeCalculationResult as validateFeeCalcSemantic,
  validateFeePreviewResponse as validatePreviewSemantic,
} from './semantic';

// ============================================================================
// FIXTURE LOADER
// ============================================================================

interface Fixture {
  description: string;
  feeCalculationResult?: unknown;
  feePreviewResponse?: unknown;
  expectedResult: {
    schemaValid: boolean;
    semanticValid: boolean;
    expectedViolations?: string[];
  };
}

function loadFixture(name: string): Fixture {
  const fixturePath = path.join(__dirname, 'fixtures', `${name}.json`);
  const content = fs.readFileSync(fixturePath, 'utf-8');
  return JSON.parse(content);
}

function loadAllFixtures(): { name: string; fixture: Fixture }[] {
  const fixturesDir = path.join(__dirname, 'fixtures');
  const files = fs.readdirSync(fixturesDir).filter(f => f.endsWith('.json'));
  
  return files.map(file => ({
    name: file.replace('.json', ''),
    fixture: loadFixture(file.replace('.json', '')),
  }));
}

// ============================================================================
// SCHEMA TESTS
// ============================================================================

describe('Tariff Provider Contract - Schema Validation', () => {
  describe('ok-* fixtures should pass schema validation', () => {
    const fixtures = loadAllFixtures().filter(f => f.name.startsWith('ok-'));
    
    test.each(fixtures)('$name: schema valid', ({ fixture }) => {
      if (fixture.feeCalculationResult) {
        const result = validateFeeCalcSchema(fixture.feeCalculationResult);
        expect(result.success).toBe(true);
      }
      
      if (fixture.feePreviewResponse) {
        const result = validatePreviewSchema(fixture.feePreviewResponse);
        expect(result.success).toBe(true);
      }
    });
  });
  
  describe('bad-* fixtures schema validation', () => {
    const fixtures = loadAllFixtures().filter(f => f.name.startsWith('bad-'));
    
    test.each(fixtures)('$name: schema validation matches expected', ({ fixture }) => {
      if (fixture.feeCalculationResult) {
        const result = validateFeeCalcSchema(fixture.feeCalculationResult);
        expect(result.success).toBe(fixture.expectedResult.schemaValid);
      }
    });
  });
  
  describe('FeeItem schema edge cases', () => {
    test('rejects negative amount', () => {
      const invalidItem = {
        type: 'FEE',
        label: 'Test',
        amount: -100,
        currency: 'TRY',
        isAutoGenerated: true,
      };
      
      const result = FeeItemSchema.safeParse(invalidItem);
      expect(result.success).toBe(false);
    });
    
    test('rejects invalid currency', () => {
      const invalidItem = {
        type: 'FEE',
        label: 'Test',
        amount: 100,
        currency: 'XYZ', // Not in allowed list
        isAutoGenerated: true,
      };
      
      const result = FeeItemSchema.safeParse(invalidItem);
      expect(result.success).toBe(false);
    });
    
    test('accepts valid fee item', () => {
      const validItem = {
        type: 'FEE',
        label: 'Başvuru Harcı',
        amount: 427.60,
        currency: 'TRY',
        isAutoGenerated: true,
        tariffCode: 'BASVURU_HARCI',
      };
      
      const result = FeeItemSchema.safeParse(validItem);
      expect(result.success).toBe(true);
    });
  });
  
  describe('FeeCalculationResult schema edge cases', () => {
    test('rejects invalid tariff year (too old)', () => {
      const invalid = {
        items: [],
        totalAmount: 0,
        tariffYear: 1990, // Too old
        calculatedAt: '2026-01-16T10:00:00Z',
      };
      
      const result = FeeCalculationResultSchema.safeParse(invalid);
      expect(result.success).toBe(false);
    });
    
    test('rejects invalid tariff year (too far future)', () => {
      const invalid = {
        items: [],
        totalAmount: 0,
        tariffYear: 2200, // Too far
        calculatedAt: '2026-01-16T10:00:00Z',
      };
      
      const result = FeeCalculationResultSchema.safeParse(invalid);
      expect(result.success).toBe(false);
    });
  });
});

// ============================================================================
// SEMANTIC TESTS
// ============================================================================

describe('Tariff Provider Contract - Semantic Validation', () => {
  describe('ok-* fixtures should pass semantic validation', () => {
    const fixtures = loadAllFixtures().filter(f => f.name.startsWith('ok-'));
    
    test.each(fixtures)('$name: semantic valid', ({ fixture }) => {
      if (fixture.feeCalculationResult) {
        const schemaResult = validateFeeCalcSchema(fixture.feeCalculationResult);
        if (schemaResult.success) {
          const semanticResult = validateFeeCalcSemantic(schemaResult.data);
          expect(semanticResult.valid).toBe(true);
        }
      }
      
      if (fixture.feePreviewResponse) {
        const schemaResult = validatePreviewSchema(fixture.feePreviewResponse);
        if (schemaResult.success) {
          const semanticResult = validatePreviewSemantic(schemaResult.data);
          expect(semanticResult.valid).toBe(true);
        }
      }
    });
  });
  
  describe('bad-* fixtures should fail semantic validation', () => {
    const fixtures = loadAllFixtures().filter(f => f.name.startsWith('bad-'));
    
    test.each(fixtures)('$name: semantic invalid with expected violations', ({ fixture }) => {
      if (fixture.feeCalculationResult) {
        const schemaResult = validateFeeCalcSchema(fixture.feeCalculationResult);
        
        if (!schemaResult.success) {
          // Schema failed, check if that was expected
          expect(fixture.expectedResult.schemaValid).toBe(false);
          return;
        }
        
        const semanticResult = validateFeeCalcSemantic(schemaResult.data);
        expect(semanticResult.valid).toBe(fixture.expectedResult.semanticValid);
        
        if (fixture.expectedResult.expectedViolations) {
          const violationRules = semanticResult.violations.map(v => v.rule);
          for (const expected of fixture.expectedResult.expectedViolations) {
            expect(violationRules).toContain(expected);
          }
        }
      }
    });
  });
  
  describe('Semantic rule: TOTAL_MISMATCH', () => {
    test('detects total not matching sum', () => {
      const result = {
        items: [
          { type: 'FEE', label: 'A', amount: 100, currency: 'TRY' as const, isAutoGenerated: true },
          { type: 'FEE', label: 'B', amount: 200, currency: 'TRY' as const, isAutoGenerated: true },
        ],
        totalAmount: 500, // Should be 300
        tariffYear: 2026,
        calculatedAt: '2026-01-16T10:00:00Z',
      };
      
      const semanticResult = validateFeeCalcSemantic(result);
      expect(semanticResult.valid).toBe(false);
      expect(semanticResult.violations.some(v => v.rule === 'TOTAL_MISMATCH')).toBe(true);
    });
    
    test('allows small rounding difference', () => {
      const result = {
        items: [
          { type: 'FEE', label: 'A', amount: 100.005, currency: 'TRY' as const, isAutoGenerated: true },
        ],
        totalAmount: 100.01, // Within tolerance
        tariffYear: 2026,
        calculatedAt: '2026-01-16T10:00:00Z',
      };
      
      const semanticResult = validateFeeCalcSemantic(result);
      expect(semanticResult.violations.filter(v => v.rule === 'TOTAL_MISMATCH')).toHaveLength(0);
    });
  });
  
  describe('Semantic rule: MIXED_CURRENCIES', () => {
    test('warns on mixed currencies', () => {
      const result = {
        items: [
          { type: 'FEE', label: 'A', amount: 100, currency: 'TRY' as const, isAutoGenerated: true },
          { type: 'FEE', label: 'B', amount: 200, currency: 'USD' as const, isAutoGenerated: true },
        ],
        totalAmount: 300,
        tariffYear: 2026,
        calculatedAt: '2026-01-16T10:00:00Z',
      };
      
      const semanticResult = validateFeeCalcSemantic(result);
      expect(semanticResult.violations.some(v => v.rule === 'MIXED_CURRENCIES')).toBe(true);
    });
  });
  
  describe('Semantic rule: EMPTY_VERSION', () => {
    test('rejects empty version', () => {
      const response = {
        estimatedFees: 100,
        estimatedAttorneyFee: 0,
        tariffYear: 2026,
        tariffVersion: '', // Empty!
      };
      
      const semanticResult = validatePreviewSemantic(response);
      expect(semanticResult.valid).toBe(false);
      expect(semanticResult.violations.some(v => v.rule === 'EMPTY_VERSION')).toBe(true);
    });
  });
});

// ============================================================================
// CONTRACT VERSION TEST
// ============================================================================

describe('Tariff Provider Contract - Version', () => {
  test('schema version is v1', () => {
    expect(TARIFF_PROVIDER_SCHEMA_VERSION).toBe('v1');
  });
});
