/**
 * Phase 5.6 - Tariff Provider Contract Schema (v1)
 * 
 * JSON shape validation using Zod.
 * Bu schema DONMUŞ - breaking change için v2 oluştur.
 * 
 * @see contracts/README.md
 */

import { z } from 'zod';

// ============================================================================
// ALLOWED VALUES
// ============================================================================

export const ALLOWED_CURRENCIES = ['TRY', 'USD', 'EUR'] as const;
export const ALLOWED_FEE_ITEM_TYPES = ['FEE', 'STAMP', 'POSTAGE', 'EXPENSE', 'PENALTY'] as const;

// ============================================================================
// FEE ITEM SCHEMA
// ============================================================================

export const FeeItemSchema = z.object({
  type: z.string().min(1),
  label: z.string().min(1),
  amount: z.number().min(0), // Non-negative
  currency: z.enum(ALLOWED_CURRENCIES),
  description: z.string().optional(),
  isAutoGenerated: z.boolean(),
  tariffCode: z.string().optional(),
});

export type FeeItem = z.infer<typeof FeeItemSchema>;

// ============================================================================
// FEE CALCULATION RESULT SCHEMA
// ============================================================================

export const FeeCalculationResultSchema = z.object({
  items: z.array(FeeItemSchema),
  totalAmount: z.number().min(0),
  tariffYear: z.number().int().min(2000).max(2100),
  calculatedAt: z.string(), // ISO datetime
});

export type FeeCalculationResult = z.infer<typeof FeeCalculationResultSchema>;

// ============================================================================
// FEE PREVIEW RESPONSE SCHEMA (for calc-preview)
// ============================================================================

export const FeePreviewResponseSchema = z.object({
  estimatedFees: z.number().min(0),
  estimatedAttorneyFee: z.number().min(0),
  tariffYear: z.number().int().min(2000).max(2100),
  tariffVersion: z.string().min(1),
  breakdown: z.array(FeeItemSchema).optional(),
  warnings: z.array(z.object({
    code: z.string(),
    message: z.string(),
    severity: z.enum(['INFO', 'WARNING', 'ERROR']),
  })).optional(),
});

export type FeePreviewResponse = z.infer<typeof FeePreviewResponseSchema>;

// ============================================================================
// TARIFF METADATA SCHEMA
// ============================================================================

export const TariffMetadataSchema = z.object({
  version: z.number().int().min(1),
  year: z.number().int().min(2000).max(2100),
  effectiveDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  source: z.string().optional(),
});

export type TariffMetadata = z.infer<typeof TariffMetadataSchema>;

// ============================================================================
// SCHEMA VERSION
// ============================================================================

export const TARIFF_PROVIDER_SCHEMA_VERSION = 'v1';

// ============================================================================
// VALIDATION HELPERS
// ============================================================================

export function validateFeeItem(data: unknown): { success: true; data: FeeItem } | { success: false; errors: z.ZodError } {
  const result = FeeItemSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, errors: result.error };
}

export function validateFeeCalculationResult(data: unknown): { success: true; data: FeeCalculationResult } | { success: false; errors: z.ZodError } {
  const result = FeeCalculationResultSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, errors: result.error };
}

export function validateFeePreviewResponse(data: unknown): { success: true; data: FeePreviewResponse } | { success: false; errors: z.ZodError } {
  const result = FeePreviewResponseSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, errors: result.error };
}
