// Mahkemeler ve Adli Kurumlar - Türkiye'deki tüm mahkeme türleri
export const MAHKEME_DATA = [
  // ==================== İSTANBUL MAHKEMELERI ====================
  // İstanbul Adliyesi
  { detsisNo: 'MHK-34-001', name: 'İstanbul 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-002', name: 'İstanbul 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-003', name: 'İstanbul 3. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-004', name: 'İstanbul 4. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-005', name: 'İstanbul 5. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-010', name: 'İstanbul 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-011', name: 'İstanbul 2. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-012', name: 'İstanbul 3. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-020', name: 'İstanbul 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-021', name: 'İstanbul 2. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-022', name: 'İstanbul 3. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-030', name: 'İstanbul 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-031', name: 'İstanbul 2. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-032', name: 'İstanbul 3. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-040', name: 'İstanbul 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-041', name: 'İstanbul 2. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-042', name: 'İstanbul 3. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-050', name: 'İstanbul 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-051', name: 'İstanbul 2. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-052', name: 'İstanbul 3. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-060', name: 'İstanbul 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-061', name: 'İstanbul 2. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-062', name: 'İstanbul 3. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-070', name: 'İstanbul 1. Sulh Ceza Hakimliği', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-071', name: 'İstanbul 2. Sulh Ceza Hakimliği', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-080', name: 'İstanbul 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-081', name: 'İstanbul 2. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-082', name: 'İstanbul 3. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-090', name: 'İstanbul 1. İcra Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-091', name: 'İstanbul 2. İcra Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-100', name: 'İstanbul 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-101', name: 'İstanbul 2. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-110', name: 'İstanbul 1. Kadastro Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-120', name: 'İstanbul 1. Fikri ve Sınai Haklar Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-121', name: 'İstanbul 2. Fikri ve Sınai Haklar Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-130', name: 'İstanbul 1. Fikri ve Sınai Haklar Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-140', name: 'İstanbul Çocuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34-141', name: 'İstanbul Çocuk Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },

  // İstanbul Anadolu Adliyesi
  { detsisNo: 'MHK-34A-001', name: 'İstanbul Anadolu 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-002', name: 'İstanbul Anadolu 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-003', name: 'İstanbul Anadolu 3. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-010', name: 'İstanbul Anadolu 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-011', name: 'İstanbul Anadolu 2. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-020', name: 'İstanbul Anadolu 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-021', name: 'İstanbul Anadolu 2. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-030', name: 'İstanbul Anadolu 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-031', name: 'İstanbul Anadolu 2. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-040', name: 'İstanbul Anadolu 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-041', name: 'İstanbul Anadolu 2. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-050', name: 'İstanbul Anadolu 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-051', name: 'İstanbul Anadolu 2. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-060', name: 'İstanbul Anadolu 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-061', name: 'İstanbul Anadolu 2. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-080', name: 'İstanbul Anadolu 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-081', name: 'İstanbul Anadolu 2. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34A-100', name: 'İstanbul Anadolu 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },

  // Bakırköy Adliyesi
  { detsisNo: 'MHK-34B-001', name: 'Bakırköy 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-002', name: 'Bakırköy 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-010', name: 'Bakırköy 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-020', name: 'Bakırköy 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-030', name: 'Bakırköy 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-040', name: 'Bakırköy 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-050', name: 'Bakırköy 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-060', name: 'Bakırköy 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },
  { detsisNo: 'MHK-34B-080', name: 'Bakırköy 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İstanbul' },

  // ==================== ANKARA MAHKEMELERI ====================
  { detsisNo: 'MHK-06-001', name: 'Ankara 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-002', name: 'Ankara 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-003', name: 'Ankara 3. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-004', name: 'Ankara 4. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-010', name: 'Ankara 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-011', name: 'Ankara 2. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-020', name: 'Ankara 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-021', name: 'Ankara 2. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-022', name: 'Ankara 3. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-030', name: 'Ankara 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-031', name: 'Ankara 2. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-040', name: 'Ankara 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-041', name: 'Ankara 2. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-050', name: 'Ankara 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-051', name: 'Ankara 2. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-060', name: 'Ankara 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-061', name: 'Ankara 2. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-070', name: 'Ankara 1. Sulh Ceza Hakimliği', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-080', name: 'Ankara 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-081', name: 'Ankara 2. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-090', name: 'Ankara 1. İcra Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-100', name: 'Ankara 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-110', name: 'Ankara 1. Kadastro Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-120', name: 'Ankara 1. Fikri ve Sınai Haklar Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-130', name: 'Ankara İdare Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-131', name: 'Ankara Vergi Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06-140', name: 'Ankara Çocuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },

  // Ankara Batı Adliyesi
  { detsisNo: 'MHK-06W-001', name: 'Ankara Batı 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06W-010', name: 'Ankara Batı 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06W-020', name: 'Ankara Batı 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06W-040', name: 'Ankara Batı 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06W-050', name: 'Ankara Batı 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06W-060', name: 'Ankara Batı 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-06W-080', name: 'Ankara Batı 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ankara' },

  // ==================== İZMİR MAHKEMELERI ====================
  { detsisNo: 'MHK-35-001', name: 'İzmir 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-002', name: 'İzmir 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-003', name: 'İzmir 3. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-010', name: 'İzmir 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-011', name: 'İzmir 2. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-020', name: 'İzmir 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-021', name: 'İzmir 2. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-030', name: 'İzmir 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-031', name: 'İzmir 2. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-040', name: 'İzmir 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-041', name: 'İzmir 2. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-050', name: 'İzmir 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-051', name: 'İzmir 2. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-060', name: 'İzmir 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-061', name: 'İzmir 2. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-070', name: 'İzmir 1. Sulh Ceza Hakimliği', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-080', name: 'İzmir 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-081', name: 'İzmir 2. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-090', name: 'İzmir 1. İcra Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-100', name: 'İzmir 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-110', name: 'İzmir 1. Kadastro Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-120', name: 'İzmir 1. Fikri ve Sınai Haklar Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-130', name: 'İzmir İdare Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35-140', name: 'İzmir Çocuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },

  // Karşıyaka Adliyesi
  { detsisNo: 'MHK-35K-001', name: 'Karşıyaka 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35K-010', name: 'Karşıyaka 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35K-020', name: 'Karşıyaka 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35K-040', name: 'Karşıyaka 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35K-050', name: 'Karşıyaka 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35K-060', name: 'Karşıyaka 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },
  { detsisNo: 'MHK-35K-080', name: 'Karşıyaka 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'İzmir' },

  // ==================== BURSA MAHKEMELERI ====================
  { detsisNo: 'MHK-16-001', name: 'Bursa 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-002', name: 'Bursa 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-010', name: 'Bursa 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-020', name: 'Bursa 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-030', name: 'Bursa 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-040', name: 'Bursa 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-050', name: 'Bursa 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-060', name: 'Bursa 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-080', name: 'Bursa 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },
  { detsisNo: 'MHK-16-100', name: 'Bursa 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'Bursa' },

  // ==================== ANTALYA MAHKEMELERI ====================
  { detsisNo: 'MHK-07-001', name: 'Antalya 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-002', name: 'Antalya 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-010', name: 'Antalya 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-020', name: 'Antalya 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-030', name: 'Antalya 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-040', name: 'Antalya 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-050', name: 'Antalya 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-060', name: 'Antalya 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-080', name: 'Antalya 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07-100', name: 'Antalya 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },

  // Alanya Adliyesi
  { detsisNo: 'MHK-07A-001', name: 'Alanya 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07A-010', name: 'Alanya 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07A-020', name: 'Alanya 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07A-040', name: 'Alanya 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07A-050', name: 'Alanya 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07A-060', name: 'Alanya 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },
  { detsisNo: 'MHK-07A-080', name: 'Alanya 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Antalya' },

  // ==================== ADANA MAHKEMELERI ====================
  { detsisNo: 'MHK-01-001', name: 'Adana 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-002', name: 'Adana 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-010', name: 'Adana 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-020', name: 'Adana 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-030', name: 'Adana 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-040', name: 'Adana 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-050', name: 'Adana 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-060', name: 'Adana 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-080', name: 'Adana 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },
  { detsisNo: 'MHK-01-100', name: 'Adana 1. Tüketici Mahkemesi', category: 'MAHKEME' as const, city: 'Adana' },

  // ==================== KOCAELİ MAHKEMELERI ====================
  { detsisNo: 'MHK-41-001', name: 'Kocaeli 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-002', name: 'Kocaeli 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-010', name: 'Kocaeli 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-020', name: 'Kocaeli 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-030', name: 'Kocaeli 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-040', name: 'Kocaeli 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-050', name: 'Kocaeli 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-060', name: 'Kocaeli 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41-080', name: 'Kocaeli 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },

  // Gebze Adliyesi
  { detsisNo: 'MHK-41G-001', name: 'Gebze 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41G-010', name: 'Gebze 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41G-020', name: 'Gebze 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41G-040', name: 'Gebze 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41G-050', name: 'Gebze 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41G-060', name: 'Gebze 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },
  { detsisNo: 'MHK-41G-080', name: 'Gebze 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kocaeli' },

  // ==================== GAZİANTEP MAHKEMELERI ====================
  { detsisNo: 'MHK-27-001', name: 'Gaziantep 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-002', name: 'Gaziantep 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-010', name: 'Gaziantep 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-020', name: 'Gaziantep 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-030', name: 'Gaziantep 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-040', name: 'Gaziantep 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-050', name: 'Gaziantep 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-060', name: 'Gaziantep 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },
  { detsisNo: 'MHK-27-080', name: 'Gaziantep 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Gaziantep' },

  // ==================== KONYA MAHKEMELERI ====================
  { detsisNo: 'MHK-42-001', name: 'Konya 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-002', name: 'Konya 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-010', name: 'Konya 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-020', name: 'Konya 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-030', name: 'Konya 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-040', name: 'Konya 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-050', name: 'Konya 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-060', name: 'Konya 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },
  { detsisNo: 'MHK-42-080', name: 'Konya 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Konya' },

  // ==================== MERSİN MAHKEMELERI ====================
  { detsisNo: 'MHK-33-001', name: 'Mersin 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-002', name: 'Mersin 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-010', name: 'Mersin 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-020', name: 'Mersin 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-030', name: 'Mersin 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-040', name: 'Mersin 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-050', name: 'Mersin 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-060', name: 'Mersin 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33-080', name: 'Mersin 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },

  // Tarsus Adliyesi
  { detsisNo: 'MHK-33T-001', name: 'Tarsus 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33T-010', name: 'Tarsus 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33T-020', name: 'Tarsus 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33T-040', name: 'Tarsus 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33T-050', name: 'Tarsus 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33T-060', name: 'Tarsus 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },
  { detsisNo: 'MHK-33T-080', name: 'Tarsus 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Mersin' },

  // ==================== DİYARBAKIR MAHKEMELERI ====================
  { detsisNo: 'MHK-21-001', name: 'Diyarbakır 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-002', name: 'Diyarbakır 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-010', name: 'Diyarbakır 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-020', name: 'Diyarbakır 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-030', name: 'Diyarbakır 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-040', name: 'Diyarbakır 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-050', name: 'Diyarbakır 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-060', name: 'Diyarbakır 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },
  { detsisNo: 'MHK-21-080', name: 'Diyarbakır 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Diyarbakır' },

  // ==================== ŞANLIURFA MAHKEMELERI ====================
  { detsisNo: 'MHK-63-001', name: 'Şanlıurfa 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-002', name: 'Şanlıurfa 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-010', name: 'Şanlıurfa 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-020', name: 'Şanlıurfa 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-040', name: 'Şanlıurfa 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-050', name: 'Şanlıurfa 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-060', name: 'Şanlıurfa 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },
  { detsisNo: 'MHK-63-080', name: 'Şanlıurfa 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Şanlıurfa' },

  // ==================== KAYSERİ MAHKEMELERI ====================
  { detsisNo: 'MHK-38-001', name: 'Kayseri 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-002', name: 'Kayseri 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-010', name: 'Kayseri 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-020', name: 'Kayseri 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-030', name: 'Kayseri 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-040', name: 'Kayseri 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-050', name: 'Kayseri 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-060', name: 'Kayseri 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },
  { detsisNo: 'MHK-38-080', name: 'Kayseri 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kayseri' },

  // ==================== ESKİŞEHİR MAHKEMELERI ====================
  { detsisNo: 'MHK-26-001', name: 'Eskişehir 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-002', name: 'Eskişehir 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-010', name: 'Eskişehir 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-020', name: 'Eskişehir 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-030', name: 'Eskişehir 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-040', name: 'Eskişehir 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-050', name: 'Eskişehir 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-060', name: 'Eskişehir 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },
  { detsisNo: 'MHK-26-080', name: 'Eskişehir 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Eskişehir' },

  // ==================== SAMSUN MAHKEMELERI ====================
  { detsisNo: 'MHK-55-001', name: 'Samsun 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-002', name: 'Samsun 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-010', name: 'Samsun 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-020', name: 'Samsun 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-030', name: 'Samsun 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-040', name: 'Samsun 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-050', name: 'Samsun 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-060', name: 'Samsun 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },
  { detsisNo: 'MHK-55-080', name: 'Samsun 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Samsun' },

  // ==================== DENİZLİ MAHKEMELERI ====================
  { detsisNo: 'MHK-20-001', name: 'Denizli 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-002', name: 'Denizli 2. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-010', name: 'Denizli 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-020', name: 'Denizli 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-030', name: 'Denizli 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-040', name: 'Denizli 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-050', name: 'Denizli 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-060', name: 'Denizli 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },
  { detsisNo: 'MHK-20-080', name: 'Denizli 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Denizli' },

  // ==================== SAKARYA MAHKEMELERI ====================
  { detsisNo: 'MHK-54-001', name: 'Sakarya 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-010', name: 'Sakarya 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-020', name: 'Sakarya 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-030', name: 'Sakarya 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-040', name: 'Sakarya 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-050', name: 'Sakarya 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-060', name: 'Sakarya 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },
  { detsisNo: 'MHK-54-080', name: 'Sakarya 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Sakarya' },

  // ==================== MANİSA MAHKEMELERI ====================
  { detsisNo: 'MHK-45-001', name: 'Manisa 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-010', name: 'Manisa 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-020', name: 'Manisa 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-030', name: 'Manisa 1. Asliye Ticaret Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-040', name: 'Manisa 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-050', name: 'Manisa 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-060', name: 'Manisa 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },
  { detsisNo: 'MHK-45-080', name: 'Manisa 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Manisa' },

  // ==================== KAHRAMANMARAŞ MAHKEMELERI ====================
  { detsisNo: 'MHK-46-001', name: 'Kahramanmaraş 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },
  { detsisNo: 'MHK-46-010', name: 'Kahramanmaraş 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },
  { detsisNo: 'MHK-46-020', name: 'Kahramanmaraş 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },
  { detsisNo: 'MHK-46-040', name: 'Kahramanmaraş 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },
  { detsisNo: 'MHK-46-050', name: 'Kahramanmaraş 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },
  { detsisNo: 'MHK-46-060', name: 'Kahramanmaraş 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },
  { detsisNo: 'MHK-46-080', name: 'Kahramanmaraş 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Kahramanmaraş' },

  // ==================== VAN MAHKEMELERI ====================
  { detsisNo: 'MHK-65-001', name: 'Van 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },
  { detsisNo: 'MHK-65-010', name: 'Van 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },
  { detsisNo: 'MHK-65-020', name: 'Van 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },
  { detsisNo: 'MHK-65-040', name: 'Van 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },
  { detsisNo: 'MHK-65-050', name: 'Van 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },
  { detsisNo: 'MHK-65-060', name: 'Van 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },
  { detsisNo: 'MHK-65-080', name: 'Van 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Van' },

  // ==================== AYDIN MAHKEMELERI ====================
  { detsisNo: 'MHK-09-001', name: 'Aydın 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },
  { detsisNo: 'MHK-09-010', name: 'Aydın 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },
  { detsisNo: 'MHK-09-020', name: 'Aydın 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },
  { detsisNo: 'MHK-09-040', name: 'Aydın 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },
  { detsisNo: 'MHK-09-050', name: 'Aydın 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },
  { detsisNo: 'MHK-09-060', name: 'Aydın 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },
  { detsisNo: 'MHK-09-080', name: 'Aydın 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Aydın' },

  // ==================== BALIKESİR MAHKEMELERI ====================
  { detsisNo: 'MHK-10-001', name: 'Balıkesir 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },
  { detsisNo: 'MHK-10-010', name: 'Balıkesir 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },
  { detsisNo: 'MHK-10-020', name: 'Balıkesir 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },
  { detsisNo: 'MHK-10-040', name: 'Balıkesir 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },
  { detsisNo: 'MHK-10-050', name: 'Balıkesir 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },
  { detsisNo: 'MHK-10-060', name: 'Balıkesir 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },
  { detsisNo: 'MHK-10-080', name: 'Balıkesir 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Balıkesir' },

  // ==================== TEKİRDAĞ MAHKEMELERI ====================
  { detsisNo: 'MHK-59-001', name: 'Tekirdağ 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59-010', name: 'Tekirdağ 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59-020', name: 'Tekirdağ 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59-040', name: 'Tekirdağ 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59-050', name: 'Tekirdağ 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59-060', name: 'Tekirdağ 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59-080', name: 'Tekirdağ 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },

  // Çorlu Adliyesi
  { detsisNo: 'MHK-59C-001', name: 'Çorlu 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59C-010', name: 'Çorlu 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59C-020', name: 'Çorlu 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59C-040', name: 'Çorlu 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59C-050', name: 'Çorlu 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59C-060', name: 'Çorlu 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },
  { detsisNo: 'MHK-59C-080', name: 'Çorlu 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Tekirdağ' },

  // ==================== TRABZON MAHKEMELERI ====================
  { detsisNo: 'MHK-61-001', name: 'Trabzon 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },
  { detsisNo: 'MHK-61-010', name: 'Trabzon 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },
  { detsisNo: 'MHK-61-020', name: 'Trabzon 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },
  { detsisNo: 'MHK-61-040', name: 'Trabzon 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },
  { detsisNo: 'MHK-61-050', name: 'Trabzon 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },
  { detsisNo: 'MHK-61-060', name: 'Trabzon 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },
  { detsisNo: 'MHK-61-080', name: 'Trabzon 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Trabzon' },

  // ==================== MALATYA MAHKEMELERI ====================
  { detsisNo: 'MHK-44-001', name: 'Malatya 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },
  { detsisNo: 'MHK-44-010', name: 'Malatya 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },
  { detsisNo: 'MHK-44-020', name: 'Malatya 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },
  { detsisNo: 'MHK-44-040', name: 'Malatya 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },
  { detsisNo: 'MHK-44-050', name: 'Malatya 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },
  { detsisNo: 'MHK-44-060', name: 'Malatya 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },
  { detsisNo: 'MHK-44-080', name: 'Malatya 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Malatya' },

  // ==================== ERZURUM MAHKEMELERI ====================
  { detsisNo: 'MHK-25-001', name: 'Erzurum 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },
  { detsisNo: 'MHK-25-010', name: 'Erzurum 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },
  { detsisNo: 'MHK-25-020', name: 'Erzurum 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },
  { detsisNo: 'MHK-25-040', name: 'Erzurum 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },
  { detsisNo: 'MHK-25-050', name: 'Erzurum 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },
  { detsisNo: 'MHK-25-060', name: 'Erzurum 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },
  { detsisNo: 'MHK-25-080', name: 'Erzurum 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Erzurum' },

  // ==================== SİVAS MAHKEMELERI ====================
  { detsisNo: 'MHK-58-001', name: 'Sivas 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },
  { detsisNo: 'MHK-58-010', name: 'Sivas 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },
  { detsisNo: 'MHK-58-020', name: 'Sivas 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },
  { detsisNo: 'MHK-58-040', name: 'Sivas 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },
  { detsisNo: 'MHK-58-050', name: 'Sivas 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },
  { detsisNo: 'MHK-58-060', name: 'Sivas 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },
  { detsisNo: 'MHK-58-080', name: 'Sivas 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Sivas' },

  // ==================== HATAY MAHKEMELERI ====================
  { detsisNo: 'MHK-31-001', name: 'Hatay 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31-010', name: 'Hatay 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31-020', name: 'Hatay 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31-040', name: 'Hatay 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31-050', name: 'Hatay 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31-060', name: 'Hatay 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31-080', name: 'Hatay 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },

  // İskenderun Adliyesi
  { detsisNo: 'MHK-31I-001', name: 'İskenderun 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31I-010', name: 'İskenderun 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31I-020', name: 'İskenderun 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31I-040', name: 'İskenderun 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31I-050', name: 'İskenderun 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31I-060', name: 'İskenderun 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },
  { detsisNo: 'MHK-31I-080', name: 'İskenderun 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Hatay' },

  // ==================== MUĞLA MAHKEMELERI ====================
  { detsisNo: 'MHK-48-001', name: 'Muğla 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48-010', name: 'Muğla 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48-020', name: 'Muğla 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48-040', name: 'Muğla 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48-050', name: 'Muğla 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48-060', name: 'Muğla 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48-080', name: 'Muğla 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },

  // Bodrum Adliyesi
  { detsisNo: 'MHK-48B-001', name: 'Bodrum 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48B-010', name: 'Bodrum 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48B-020', name: 'Bodrum 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48B-040', name: 'Bodrum 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48B-050', name: 'Bodrum 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48B-060', name: 'Bodrum 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48B-080', name: 'Bodrum 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },

  // Fethiye Adliyesi
  { detsisNo: 'MHK-48F-001', name: 'Fethiye 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48F-010', name: 'Fethiye 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48F-020', name: 'Fethiye 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48F-040', name: 'Fethiye 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48F-050', name: 'Fethiye 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48F-060', name: 'Fethiye 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48F-080', name: 'Fethiye 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },

  // Marmaris Adliyesi
  { detsisNo: 'MHK-48M-001', name: 'Marmaris 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48M-010', name: 'Marmaris 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48M-020', name: 'Marmaris 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48M-040', name: 'Marmaris 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48M-050', name: 'Marmaris 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48M-060', name: 'Marmaris 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },
  { detsisNo: 'MHK-48M-080', name: 'Marmaris 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Muğla' },

  // ==================== ELAZIĞ MAHKEMELERI ====================
  { detsisNo: 'MHK-23-001', name: 'Elazığ 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },
  { detsisNo: 'MHK-23-010', name: 'Elazığ 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },
  { detsisNo: 'MHK-23-020', name: 'Elazığ 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },
  { detsisNo: 'MHK-23-040', name: 'Elazığ 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },
  { detsisNo: 'MHK-23-050', name: 'Elazığ 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },
  { detsisNo: 'MHK-23-060', name: 'Elazığ 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },
  { detsisNo: 'MHK-23-080', name: 'Elazığ 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Elazığ' },

  // ==================== ORDU MAHKEMELERI ====================
  { detsisNo: 'MHK-52-001', name: 'Ordu 1. Asliye Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },
  { detsisNo: 'MHK-52-010', name: 'Ordu 1. Asliye Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },
  { detsisNo: 'MHK-52-020', name: 'Ordu 1. Ağır Ceza Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },
  { detsisNo: 'MHK-52-040', name: 'Ordu 1. İş Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },
  { detsisNo: 'MHK-52-050', name: 'Ordu 1. Aile Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },
  { detsisNo: 'MHK-52-060', name: 'Ordu 1. Sulh Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },
  { detsisNo: 'MHK-52-080', name: 'Ordu 1. İcra Hukuk Mahkemesi', category: 'MAHKEME' as const, city: 'Ordu' },

  // ==================== YÜKSEK MAHKEMELER ====================
  { detsisNo: 'MHK-YRG-001', name: 'Yargıtay', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-002', name: 'Yargıtay 1. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-003', name: 'Yargıtay 2. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-004', name: 'Yargıtay 3. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-005', name: 'Yargıtay 4. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-006', name: 'Yargıtay 5. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-007', name: 'Yargıtay 6. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-008', name: 'Yargıtay 7. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-009', name: 'Yargıtay 8. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-010', name: 'Yargıtay 9. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-011', name: 'Yargıtay 10. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-012', name: 'Yargıtay 11. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-013', name: 'Yargıtay 12. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-014', name: 'Yargıtay 13. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-015', name: 'Yargıtay 14. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-016', name: 'Yargıtay 15. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-017', name: 'Yargıtay 16. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-018', name: 'Yargıtay 17. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-019', name: 'Yargıtay 18. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-020', name: 'Yargıtay 19. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-021', name: 'Yargıtay 20. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-022', name: 'Yargıtay 21. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-023', name: 'Yargıtay 22. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-024', name: 'Yargıtay 23. Hukuk Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-050', name: 'Yargıtay 1. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-051', name: 'Yargıtay 2. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-052', name: 'Yargıtay 3. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-053', name: 'Yargıtay 4. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-054', name: 'Yargıtay 5. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-055', name: 'Yargıtay 6. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-056', name: 'Yargıtay 7. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-057', name: 'Yargıtay 8. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-058', name: 'Yargıtay 9. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-059', name: 'Yargıtay 10. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-060', name: 'Yargıtay 11. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-061', name: 'Yargıtay 12. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-062', name: 'Yargıtay 13. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-063', name: 'Yargıtay 14. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-064', name: 'Yargıtay 15. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-065', name: 'Yargıtay 16. Ceza Dairesi', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-100', name: 'Yargıtay Hukuk Genel Kurulu', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-YRG-101', name: 'Yargıtay Ceza Genel Kurulu', category: 'MAHKEME' as const, city: 'Ankara' },

  // Danıştay
  { detsisNo: 'MHK-DAN-001', name: 'Danıştay', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-DAN-002', name: 'Danıştay 1. Daire', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-DAN-003', name: 'Danıştay 2. Daire', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-DAN-004', name: 'Danıştay 3. Daire', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-DAN-005', name: 'Danıştay 4. Daire', category: 'MAHKEME' as const, city: 'Ankara' },
  { detsisNo: 'MHK-DAN-006', name: 'Danıştay 5. Daire', category: 'MAHKEME' as const, city: 'Ankara' },
];
