// Türkiye Belediyeleri - İl ve İlçe Belediyeleri
// 30 Büyükşehir + 51 İl + İlçe Belediyeleri

export const BELEDIYE_DATA = [
  // ==================== ADANA İLÇE BELEDİYELERİ ====================
  { detsisNo: '1100', name: 'Aladağ Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Aladağ' },
  { detsisNo: '1101', name: 'Ceyhan Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Ceyhan' },
  { detsisNo: '1102', name: 'Çukurova Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Çukurova' },
  { detsisNo: '1103', name: 'Feke Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Feke' },
  { detsisNo: '1104', name: 'İmamoğlu Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'İmamoğlu' },
  { detsisNo: '1105', name: 'Karaisalı Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Karaisalı' },
  { detsisNo: '1106', name: 'Karataş Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Karataş' },
  { detsisNo: '1107', name: 'Kozan Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Kozan' },
  { detsisNo: '1108', name: 'Pozantı Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Pozantı' },
  { detsisNo: '1109', name: 'Saimbeyli Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Saimbeyli' },
  { detsisNo: '1110', name: 'Sarıçam Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Sarıçam' },
  { detsisNo: '1111', name: 'Seyhan Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Seyhan' },
  { detsisNo: '1112', name: 'Tufanbeyli Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Tufanbeyli' },
  { detsisNo: '1113', name: 'Yumurtalık Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Yumurtalık' },
  { detsisNo: '1114', name: 'Yüreğir Belediyesi', category: 'BELEDIYE' as const, city: 'Adana', district: 'Yüreğir' },

  // ==================== ANKARA İLÇE BELEDİYELERİ ====================
  { detsisNo: '1200', name: 'Akyurt Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Akyurt' },
  { detsisNo: '1201', name: 'Altındağ Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Altındağ' },
  { detsisNo: '1202', name: 'Ayaş Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Ayaş' },
  { detsisNo: '1203', name: 'Bala Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Bala' },
  { detsisNo: '1204', name: 'Beypazarı Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Beypazarı' },
  { detsisNo: '1205', name: 'Çamlıdere Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Çamlıdere' },
  { detsisNo: '1206', name: 'Çankaya Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Çankaya' },
  { detsisNo: '1207', name: 'Çubuk Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Çubuk' },
  { detsisNo: '1208', name: 'Elmadağ Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Elmadağ' },
  { detsisNo: '1209', name: 'Etimesgut Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Etimesgut' },
  { detsisNo: '1210', name: 'Evren Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Evren' },
  { detsisNo: '1211', name: 'Gölbaşı Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Gölbaşı' },
  { detsisNo: '1212', name: 'Güdül Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Güdül' },
  { detsisNo: '1213', name: 'Haymana Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Haymana' },
  { detsisNo: '1214', name: 'Kahramankazan Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Kahramankazan' },
  { detsisNo: '1215', name: 'Kalecik Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Kalecik' },
  { detsisNo: '1216', name: 'Keçiören Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Keçiören' },
  { detsisNo: '1217', name: 'Kızılcahamam Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Kızılcahamam' },
  { detsisNo: '1218', name: 'Mamak Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Mamak' },
  { detsisNo: '1219', name: 'Nallıhan Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Nallıhan' },
  { detsisNo: '1220', name: 'Polatlı Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Polatlı' },
  { detsisNo: '1221', name: 'Pursaklar Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Pursaklar' },
  { detsisNo: '1222', name: 'Sincan Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Sincan' },
  { detsisNo: '1223', name: 'Şereflikoçhisar Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Şereflikoçhisar' },
  { detsisNo: '1224', name: 'Yenimahalle Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara', district: 'Yenimahalle' },

  // ==================== İSTANBUL İLÇE BELEDİYELERİ ====================
  { detsisNo: '1300', name: 'Adalar Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Adalar' },
  { detsisNo: '1301', name: 'Arnavutköy Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Arnavutköy' },
  { detsisNo: '1302', name: 'Ataşehir Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Ataşehir' },
  { detsisNo: '1303', name: 'Avcılar Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Avcılar' },
  { detsisNo: '1304', name: 'Bağcılar Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Bağcılar' },
  { detsisNo: '1305', name: 'Bahçelievler Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Bahçelievler' },
  { detsisNo: '1306', name: 'Bakırköy Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Bakırköy' },
  { detsisNo: '1307', name: 'Başakşehir Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Başakşehir' },
  { detsisNo: '1308', name: 'Bayrampaşa Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Bayrampaşa' },
  { detsisNo: '1309', name: 'Beşiktaş Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Beşiktaş' },
  { detsisNo: '1310', name: 'Beykoz Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Beykoz' },
  { detsisNo: '1311', name: 'Beylikdüzü Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Beylikdüzü' },
  { detsisNo: '1312', name: 'Beyoğlu Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Beyoğlu' },
  { detsisNo: '1313', name: 'Büyükçekmece Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Büyükçekmece' },
  { detsisNo: '1314', name: 'Çatalca Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Çatalca' },
  { detsisNo: '1315', name: 'Çekmeköy Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Çekmeköy' },
  { detsisNo: '1316', name: 'Esenler Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Esenler' },
  { detsisNo: '1317', name: 'Esenyurt Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Esenyurt' },
  { detsisNo: '1318', name: 'Eyüpsultan Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Eyüpsultan' },
  { detsisNo: '1319', name: 'Fatih Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Fatih' },
  { detsisNo: '1320', name: 'Gaziosmanpaşa Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Gaziosmanpaşa' },
  { detsisNo: '1321', name: 'Güngören Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Güngören' },
  { detsisNo: '1322', name: 'Kadıköy Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Kadıköy' },
  { detsisNo: '1323', name: 'Kağıthane Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Kağıthane' },
  { detsisNo: '1324', name: 'Kartal Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Kartal' },
  { detsisNo: '1325', name: 'Küçükçekmece Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Küçükçekmece' },
  { detsisNo: '1326', name: 'Maltepe Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Maltepe' },
  { detsisNo: '1327', name: 'Pendik Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Pendik' },
  { detsisNo: '1328', name: 'Sancaktepe Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Sancaktepe' },
  { detsisNo: '1329', name: 'Sarıyer Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Sarıyer' },
  { detsisNo: '1330', name: 'Silivri Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Silivri' },
  { detsisNo: '1331', name: 'Sultanbeyli Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Sultanbeyli' },
  { detsisNo: '1332', name: 'Sultangazi Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Sultangazi' },
  { detsisNo: '1333', name: 'Şile Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Şile' },
  { detsisNo: '1334', name: 'Şişli Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Şişli' },
  { detsisNo: '1335', name: 'Tuzla Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Tuzla' },
  { detsisNo: '1336', name: 'Ümraniye Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Ümraniye' },
  { detsisNo: '1337', name: 'Üsküdar Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Üsküdar' },
  { detsisNo: '1338', name: 'Zeytinburnu Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul', district: 'Zeytinburnu' },

  // ==================== İZMİR İLÇE BELEDİYELERİ ====================
  { detsisNo: '1400', name: 'Aliağa Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Aliağa' },
  { detsisNo: '1401', name: 'Balçova Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Balçova' },
  { detsisNo: '1402', name: 'Bayındır Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Bayındır' },
  { detsisNo: '1403', name: 'Bayraklı Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Bayraklı' },
  { detsisNo: '1404', name: 'Bergama Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Bergama' },
  { detsisNo: '1405', name: 'Beydağ Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Beydağ' },
  { detsisNo: '1406', name: 'Bornova Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Bornova' },
  { detsisNo: '1407', name: 'Buca Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Buca' },
  { detsisNo: '1408', name: 'Çeşme Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Çeşme' },
  { detsisNo: '1409', name: 'Çiğli Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Çiğli' },
  { detsisNo: '1410', name: 'Dikili Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Dikili' },
  { detsisNo: '1411', name: 'Foça Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Foça' },
  { detsisNo: '1412', name: 'Gaziemir Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Gaziemir' },
  { detsisNo: '1413', name: 'Güzelbahçe Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Güzelbahçe' },
  { detsisNo: '1414', name: 'Karabağlar Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Karabağlar' },
  { detsisNo: '1415', name: 'Karaburun Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Karaburun' },
  { detsisNo: '1416', name: 'Karşıyaka Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Karşıyaka' },
  { detsisNo: '1417', name: 'Kemalpaşa Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Kemalpaşa' },
  { detsisNo: '1418', name: 'Kınık Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Kınık' },
  { detsisNo: '1419', name: 'Kiraz Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Kiraz' },
  { detsisNo: '1420', name: 'Konak Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Konak' },
  { detsisNo: '1421', name: 'Menderes Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Menderes' },
  { detsisNo: '1422', name: 'Menemen Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Menemen' },
  { detsisNo: '1423', name: 'Narlıdere Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Narlıdere' },
  { detsisNo: '1424', name: 'Ödemiş Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Ödemiş' },
  { detsisNo: '1425', name: 'Seferihisar Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Seferihisar' },
  { detsisNo: '1426', name: 'Selçuk Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Selçuk' },
  { detsisNo: '1427', name: 'Tire Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Tire' },
  { detsisNo: '1428', name: 'Torbalı Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Torbalı' },
  { detsisNo: '1429', name: 'Urla Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir', district: 'Urla' },
];


// ==================== BURSA İLÇE BELEDİYELERİ ====================
export const BURSA_BELEDIYE = [
  { detsisNo: '1500', name: 'Büyükorhan Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Büyükorhan' },
  { detsisNo: '1501', name: 'Gemlik Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Gemlik' },
  { detsisNo: '1502', name: 'Gürsu Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Gürsu' },
  { detsisNo: '1503', name: 'Harmancık Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Harmancık' },
  { detsisNo: '1504', name: 'İnegöl Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'İnegöl' },
  { detsisNo: '1505', name: 'İznik Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'İznik' },
  { detsisNo: '1506', name: 'Karacabey Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Karacabey' },
  { detsisNo: '1507', name: 'Keles Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Keles' },
  { detsisNo: '1508', name: 'Kestel Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Kestel' },
  { detsisNo: '1509', name: 'Mudanya Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Mudanya' },
  { detsisNo: '1510', name: 'Mustafakemalpaşa Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Mustafakemalpaşa' },
  { detsisNo: '1511', name: 'Nilüfer Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Nilüfer' },
  { detsisNo: '1512', name: 'Orhaneli Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Orhaneli' },
  { detsisNo: '1513', name: 'Orhangazi Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Orhangazi' },
  { detsisNo: '1514', name: 'Osmangazi Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Osmangazi' },
  { detsisNo: '1515', name: 'Yenişehir Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Yenişehir' },
  { detsisNo: '1516', name: 'Yıldırım Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa', district: 'Yıldırım' },
];

// ==================== ANTALYA İLÇE BELEDİYELERİ ====================
export const ANTALYA_BELEDIYE = [
  { detsisNo: '1600', name: 'Akseki Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Akseki' },
  { detsisNo: '1601', name: 'Aksu Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Aksu' },
  { detsisNo: '1602', name: 'Alanya Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Alanya' },
  { detsisNo: '1603', name: 'Demre Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Demre' },
  { detsisNo: '1604', name: 'Döşemealtı Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Döşemealtı' },
  { detsisNo: '1605', name: 'Elmalı Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Elmalı' },
  { detsisNo: '1606', name: 'Finike Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Finike' },
  { detsisNo: '1607', name: 'Gazipaşa Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Gazipaşa' },
  { detsisNo: '1608', name: 'Gündoğmuş Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Gündoğmuş' },
  { detsisNo: '1609', name: 'İbradı Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'İbradı' },
  { detsisNo: '1610', name: 'Kaş Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Kaş' },
  { detsisNo: '1611', name: 'Kemer Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Kemer' },
  { detsisNo: '1612', name: 'Kepez Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Kepez' },
  { detsisNo: '1613', name: 'Konyaaltı Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Konyaaltı' },
  { detsisNo: '1614', name: 'Korkuteli Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Korkuteli' },
  { detsisNo: '1615', name: 'Kumluca Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Kumluca' },
  { detsisNo: '1616', name: 'Manavgat Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Manavgat' },
  { detsisNo: '1617', name: 'Muratpaşa Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Muratpaşa' },
  { detsisNo: '1618', name: 'Serik Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya', district: 'Serik' },
];

// ==================== KOCAELİ İLÇE BELEDİYELERİ ====================
export const KOCAELI_BELEDIYE = [
  { detsisNo: '1700', name: 'Başiskele Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Başiskele' },
  { detsisNo: '1701', name: 'Çayırova Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Çayırova' },
  { detsisNo: '1702', name: 'Darıca Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Darıca' },
  { detsisNo: '1703', name: 'Derince Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Derince' },
  { detsisNo: '1704', name: 'Dilovası Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Dilovası' },
  { detsisNo: '1705', name: 'Gebze Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Gebze' },
  { detsisNo: '1706', name: 'Gölcük Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Gölcük' },
  { detsisNo: '1707', name: 'İzmit Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'İzmit' },
  { detsisNo: '1708', name: 'Kandıra Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Kandıra' },
  { detsisNo: '1709', name: 'Karamürsel Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Karamürsel' },
  { detsisNo: '1710', name: 'Kartepe Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Kartepe' },
  { detsisNo: '1711', name: 'Körfez Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli', district: 'Körfez' },
];

// ==================== KONYA İLÇE BELEDİYELERİ ====================
export const KONYA_BELEDIYE = [
  { detsisNo: '1800', name: 'Ahırlı Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Ahırlı' },
  { detsisNo: '1801', name: 'Akören Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Akören' },
  { detsisNo: '1802', name: 'Akşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Akşehir' },
  { detsisNo: '1803', name: 'Altınekin Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Altınekin' },
  { detsisNo: '1804', name: 'Beyşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Beyşehir' },
  { detsisNo: '1805', name: 'Bozkır Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Bozkır' },
  { detsisNo: '1806', name: 'Cihanbeyli Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Cihanbeyli' },
  { detsisNo: '1807', name: 'Çeltik Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Çeltik' },
  { detsisNo: '1808', name: 'Çumra Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Çumra' },
  { detsisNo: '1809', name: 'Derbent Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Derbent' },
  { detsisNo: '1810', name: 'Derebucak Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Derebucak' },
  { detsisNo: '1811', name: 'Doğanhisar Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Doğanhisar' },
  { detsisNo: '1812', name: 'Emirgazi Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Emirgazi' },
  { detsisNo: '1813', name: 'Ereğli Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Ereğli' },
  { detsisNo: '1814', name: 'Güneysınır Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Güneysınır' },
  { detsisNo: '1815', name: 'Hadim Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Hadim' },
  { detsisNo: '1816', name: 'Halkapınar Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Halkapınar' },
  { detsisNo: '1817', name: 'Hüyük Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Hüyük' },
  { detsisNo: '1818', name: 'Ilgın Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Ilgın' },
  { detsisNo: '1819', name: 'Kadınhanı Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Kadınhanı' },
  { detsisNo: '1820', name: 'Karapınar Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Karapınar' },
  { detsisNo: '1821', name: 'Karatay Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Karatay' },
  { detsisNo: '1822', name: 'Kulu Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Kulu' },
  { detsisNo: '1823', name: 'Meram Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Meram' },
  { detsisNo: '1824', name: 'Sarayönü Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Sarayönü' },
  { detsisNo: '1825', name: 'Selçuklu Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Selçuklu' },
  { detsisNo: '1826', name: 'Seydişehir Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Seydişehir' },
  { detsisNo: '1827', name: 'Taşkent Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Taşkent' },
  { detsisNo: '1828', name: 'Tuzlukçu Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Tuzlukçu' },
  { detsisNo: '1829', name: 'Yalıhüyük Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Yalıhüyük' },
  { detsisNo: '1830', name: 'Yunak Belediyesi', category: 'BELEDIYE' as const, city: 'Konya', district: 'Yunak' },
];

// Tüm belediye verilerini birleştir
export const ALL_BELEDIYE_DATA = [
  ...BELEDIYE_DATA,
  ...BURSA_BELEDIYE,
  ...ANTALYA_BELEDIYE,
  ...KOCAELI_BELEDIYE,
  ...KONYA_BELEDIYE,
];
