// Büyükşehir Belediyeleri ve Üniversiteler
export const EXTENDED_INSTITUTIONS_DATA = [
  // ==================== BÜYÜKŞEHİR BELEDİYELERİ ====================
  { detsisNo: '500', name: 'Adana Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Adana' },
  { detsisNo: '501', name: 'Ankara Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Ankara' },
  { detsisNo: '502', name: 'Antalya Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Antalya' },
  { detsisNo: '503', name: 'Aydın Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Aydın' },
  { detsisNo: '504', name: 'Balıkesir Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Balıkesir' },
  { detsisNo: '505', name: 'Bursa Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Bursa' },
  { detsisNo: '506', name: 'Denizli Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Denizli' },
  { detsisNo: '507', name: 'Diyarbakır Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Diyarbakır' },
  { detsisNo: '508', name: 'Erzurum Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Erzurum' },
  { detsisNo: '509', name: 'Eskişehir Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Eskişehir' },
  { detsisNo: '510', name: 'Gaziantep Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Gaziantep' },
  { detsisNo: '511', name: 'Hatay Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Hatay' },
  { detsisNo: '512', name: 'İstanbul Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'İstanbul' },
  { detsisNo: '513', name: 'İzmir Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'İzmir' },
  { detsisNo: '514', name: 'Kahramanmaraş Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Kahramanmaraş' },
  { detsisNo: '515', name: 'Kayseri Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Kayseri' },
  { detsisNo: '516', name: 'Kocaeli Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Kocaeli' },
  { detsisNo: '517', name: 'Konya Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Konya' },
  { detsisNo: '518', name: 'Malatya Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Malatya' },
  { detsisNo: '519', name: 'Manisa Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Manisa' },
  { detsisNo: '520', name: 'Mardin Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Mardin' },
  { detsisNo: '521', name: 'Mersin Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Mersin' },
  { detsisNo: '522', name: 'Muğla Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Muğla' },
  { detsisNo: '523', name: 'Ordu Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Ordu' },
  { detsisNo: '524', name: 'Sakarya Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Sakarya' },
  { detsisNo: '525', name: 'Samsun Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Samsun' },
  { detsisNo: '526', name: 'Şanlıurfa Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Şanlıurfa' },
  { detsisNo: '527', name: 'Tekirdağ Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Tekirdağ' },
  { detsisNo: '528', name: 'Trabzon Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Trabzon' },
  { detsisNo: '529', name: 'Van Büyükşehir Belediyesi', category: 'BELEDIYE' as const, city: 'Van' },

  // ==================== DEVLET ÜNİVERSİTELERİ ====================
  { detsisNo: '600', name: 'Ankara Üniversitesi', category: 'UNIVERSITE' as const, city: 'Ankara' },
  { detsisNo: '601', name: 'İstanbul Üniversitesi', category: 'UNIVERSITE' as const, city: 'İstanbul' },
  { detsisNo: '602', name: 'İstanbul Teknik Üniversitesi', category: 'UNIVERSITE' as const, city: 'İstanbul' },
  { detsisNo: '603', name: 'Boğaziçi Üniversitesi', category: 'UNIVERSITE' as const, city: 'İstanbul' },
  { detsisNo: '604', name: 'Orta Doğu Teknik Üniversitesi', category: 'UNIVERSITE' as const, city: 'Ankara' },
  { detsisNo: '605', name: 'Hacettepe Üniversitesi', category: 'UNIVERSITE' as const, city: 'Ankara' },
  { detsisNo: '606', name: 'Ege Üniversitesi', category: 'UNIVERSITE' as const, city: 'İzmir' },
  { detsisNo: '607', name: 'Dokuz Eylül Üniversitesi', category: 'UNIVERSITE' as const, city: 'İzmir' },
  { detsisNo: '608', name: 'Gazi Üniversitesi', category: 'UNIVERSITE' as const, city: 'Ankara' },
  { detsisNo: '609', name: 'Marmara Üniversitesi', category: 'UNIVERSITE' as const, city: 'İstanbul' },
  { detsisNo: '610', name: 'Yıldız Teknik Üniversitesi', category: 'UNIVERSITE' as const, city: 'İstanbul' },
  { detsisNo: '611', name: 'Uludağ Üniversitesi', category: 'UNIVERSITE' as const, city: 'Bursa' },
  { detsisNo: '612', name: 'Anadolu Üniversitesi', category: 'UNIVERSITE' as const, city: 'Eskişehir' },
  { detsisNo: '613', name: 'Selçuk Üniversitesi', category: 'UNIVERSITE' as const, city: 'Konya' },
  { detsisNo: '614', name: 'Akdeniz Üniversitesi', category: 'UNIVERSITE' as const, city: 'Antalya' },
  { detsisNo: '615', name: 'Çukurova Üniversitesi', category: 'UNIVERSITE' as const, city: 'Adana' },
  { detsisNo: '616', name: 'Karadeniz Teknik Üniversitesi', category: 'UNIVERSITE' as const, city: 'Trabzon' },
  { detsisNo: '617', name: 'Atatürk Üniversitesi', category: 'UNIVERSITE' as const, city: 'Erzurum' },
  { detsisNo: '618', name: 'Erciyes Üniversitesi', category: 'UNIVERSITE' as const, city: 'Kayseri' },
  { detsisNo: '619', name: 'Ondokuz Mayıs Üniversitesi', category: 'UNIVERSITE' as const, city: 'Samsun' },
  { detsisNo: '620', name: 'Fırat Üniversitesi', category: 'UNIVERSITE' as const, city: 'Elazığ' },
  { detsisNo: '621', name: 'İnönü Üniversitesi', category: 'UNIVERSITE' as const, city: 'Malatya' },
  { detsisNo: '622', name: 'Dicle Üniversitesi', category: 'UNIVERSITE' as const, city: 'Diyarbakır' },
  { detsisNo: '623', name: 'Gaziantep Üniversitesi', category: 'UNIVERSITE' as const, city: 'Gaziantep' },
  { detsisNo: '624', name: 'Mersin Üniversitesi', category: 'UNIVERSITE' as const, city: 'Mersin' },
  { detsisNo: '625', name: 'Pamukkale Üniversitesi', category: 'UNIVERSITE' as const, city: 'Denizli' },
  { detsisNo: '626', name: 'Kocaeli Üniversitesi', category: 'UNIVERSITE' as const, city: 'Kocaeli' },
  { detsisNo: '627', name: 'Sakarya Üniversitesi', category: 'UNIVERSITE' as const, city: 'Sakarya' },
  { detsisNo: '628', name: 'Trakya Üniversitesi', category: 'UNIVERSITE' as const, city: 'Edirne' },
  { detsisNo: '629', name: 'Süleyman Demirel Üniversitesi', category: 'UNIVERSITE' as const, city: 'Isparta' },

  // ==================== VALİLİKLER (81 İL) ====================
  { detsisNo: '700', name: 'Adana Valiliği', category: 'VALILIK' as const, city: 'Adana' },
  { detsisNo: '701', name: 'Adıyaman Valiliği', category: 'VALILIK' as const, city: 'Adıyaman' },
  { detsisNo: '702', name: 'Afyonkarahisar Valiliği', category: 'VALILIK' as const, city: 'Afyonkarahisar' },
  { detsisNo: '703', name: 'Ağrı Valiliği', category: 'VALILIK' as const, city: 'Ağrı' },
  { detsisNo: '704', name: 'Amasya Valiliği', category: 'VALILIK' as const, city: 'Amasya' },
  { detsisNo: '705', name: 'Ankara Valiliği', category: 'VALILIK' as const, city: 'Ankara' },
  { detsisNo: '706', name: 'Antalya Valiliği', category: 'VALILIK' as const, city: 'Antalya' },
  { detsisNo: '707', name: 'Artvin Valiliği', category: 'VALILIK' as const, city: 'Artvin' },
  { detsisNo: '708', name: 'Aydın Valiliği', category: 'VALILIK' as const, city: 'Aydın' },
  { detsisNo: '709', name: 'Balıkesir Valiliği', category: 'VALILIK' as const, city: 'Balıkesir' },
  { detsisNo: '710', name: 'Bilecik Valiliği', category: 'VALILIK' as const, city: 'Bilecik' },
  { detsisNo: '711', name: 'Bingöl Valiliği', category: 'VALILIK' as const, city: 'Bingöl' },
  { detsisNo: '712', name: 'Bitlis Valiliği', category: 'VALILIK' as const, city: 'Bitlis' },
  { detsisNo: '713', name: 'Bolu Valiliği', category: 'VALILIK' as const, city: 'Bolu' },
  { detsisNo: '714', name: 'Burdur Valiliği', category: 'VALILIK' as const, city: 'Burdur' },
  { detsisNo: '715', name: 'Bursa Valiliği', category: 'VALILIK' as const, city: 'Bursa' },
  { detsisNo: '716', name: 'Çanakkale Valiliği', category: 'VALILIK' as const, city: 'Çanakkale' },
  { detsisNo: '717', name: 'Çankırı Valiliği', category: 'VALILIK' as const, city: 'Çankırı' },
  { detsisNo: '718', name: 'Çorum Valiliği', category: 'VALILIK' as const, city: 'Çorum' },
  { detsisNo: '719', name: 'Denizli Valiliği', category: 'VALILIK' as const, city: 'Denizli' },
  { detsisNo: '720', name: 'Diyarbakır Valiliği', category: 'VALILIK' as const, city: 'Diyarbakır' },
  { detsisNo: '721', name: 'Edirne Valiliği', category: 'VALILIK' as const, city: 'Edirne' },
  { detsisNo: '722', name: 'Elazığ Valiliği', category: 'VALILIK' as const, city: 'Elazığ' },
  { detsisNo: '723', name: 'Erzincan Valiliği', category: 'VALILIK' as const, city: 'Erzincan' },
  { detsisNo: '724', name: 'Erzurum Valiliği', category: 'VALILIK' as const, city: 'Erzurum' },
  { detsisNo: '725', name: 'Eskişehir Valiliği', category: 'VALILIK' as const, city: 'Eskişehir' },
  { detsisNo: '726', name: 'Gaziantep Valiliği', category: 'VALILIK' as const, city: 'Gaziantep' },
  { detsisNo: '727', name: 'Giresun Valiliği', category: 'VALILIK' as const, city: 'Giresun' },
  { detsisNo: '728', name: 'Gümüşhane Valiliği', category: 'VALILIK' as const, city: 'Gümüşhane' },
  { detsisNo: '729', name: 'Hakkari Valiliği', category: 'VALILIK' as const, city: 'Hakkari' },
  { detsisNo: '730', name: 'Hatay Valiliği', category: 'VALILIK' as const, city: 'Hatay' },
  { detsisNo: '731', name: 'Isparta Valiliği', category: 'VALILIK' as const, city: 'Isparta' },
  { detsisNo: '732', name: 'Mersin Valiliği', category: 'VALILIK' as const, city: 'Mersin' },
  { detsisNo: '733', name: 'İstanbul Valiliği', category: 'VALILIK' as const, city: 'İstanbul' },
  { detsisNo: '734', name: 'İzmir Valiliği', category: 'VALILIK' as const, city: 'İzmir' },
  { detsisNo: '735', name: 'Kars Valiliği', category: 'VALILIK' as const, city: 'Kars' },
  { detsisNo: '736', name: 'Kastamonu Valiliği', category: 'VALILIK' as const, city: 'Kastamonu' },
  { detsisNo: '737', name: 'Kayseri Valiliği', category: 'VALILIK' as const, city: 'Kayseri' },
  { detsisNo: '738', name: 'Kırklareli Valiliği', category: 'VALILIK' as const, city: 'Kırklareli' },
  { detsisNo: '739', name: 'Kırşehir Valiliği', category: 'VALILIK' as const, city: 'Kırşehir' },
  { detsisNo: '740', name: 'Kocaeli Valiliği', category: 'VALILIK' as const, city: 'Kocaeli' },
  { detsisNo: '741', name: 'Konya Valiliği', category: 'VALILIK' as const, city: 'Konya' },
  { detsisNo: '742', name: 'Kütahya Valiliği', category: 'VALILIK' as const, city: 'Kütahya' },
  { detsisNo: '743', name: 'Malatya Valiliği', category: 'VALILIK' as const, city: 'Malatya' },
  { detsisNo: '744', name: 'Manisa Valiliği', category: 'VALILIK' as const, city: 'Manisa' },
  { detsisNo: '745', name: 'Kahramanmaraş Valiliği', category: 'VALILIK' as const, city: 'Kahramanmaraş' },
  { detsisNo: '746', name: 'Mardin Valiliği', category: 'VALILIK' as const, city: 'Mardin' },
  { detsisNo: '747', name: 'Muğla Valiliği', category: 'VALILIK' as const, city: 'Muğla' },
  { detsisNo: '748', name: 'Muş Valiliği', category: 'VALILIK' as const, city: 'Muş' },
  { detsisNo: '749', name: 'Nevşehir Valiliği', category: 'VALILIK' as const, city: 'Nevşehir' },
  { detsisNo: '750', name: 'Niğde Valiliği', category: 'VALILIK' as const, city: 'Niğde' },
  { detsisNo: '751', name: 'Ordu Valiliği', category: 'VALILIK' as const, city: 'Ordu' },
  { detsisNo: '752', name: 'Rize Valiliği', category: 'VALILIK' as const, city: 'Rize' },
  { detsisNo: '753', name: 'Sakarya Valiliği', category: 'VALILIK' as const, city: 'Sakarya' },
  { detsisNo: '754', name: 'Samsun Valiliği', category: 'VALILIK' as const, city: 'Samsun' },
  { detsisNo: '755', name: 'Siirt Valiliği', category: 'VALILIK' as const, city: 'Siirt' },
  { detsisNo: '756', name: 'Sinop Valiliği', category: 'VALILIK' as const, city: 'Sinop' },
  { detsisNo: '757', name: 'Sivas Valiliği', category: 'VALILIK' as const, city: 'Sivas' },
  { detsisNo: '758', name: 'Tekirdağ Valiliği', category: 'VALILIK' as const, city: 'Tekirdağ' },
  { detsisNo: '759', name: 'Tokat Valiliği', category: 'VALILIK' as const, city: 'Tokat' },
  { detsisNo: '760', name: 'Trabzon Valiliği', category: 'VALILIK' as const, city: 'Trabzon' },
  { detsisNo: '761', name: 'Tunceli Valiliği', category: 'VALILIK' as const, city: 'Tunceli' },
  { detsisNo: '762', name: 'Şanlıurfa Valiliği', category: 'VALILIK' as const, city: 'Şanlıurfa' },
  { detsisNo: '763', name: 'Uşak Valiliği', category: 'VALILIK' as const, city: 'Uşak' },
  { detsisNo: '764', name: 'Van Valiliği', category: 'VALILIK' as const, city: 'Van' },
  { detsisNo: '765', name: 'Yozgat Valiliği', category: 'VALILIK' as const, city: 'Yozgat' },
  { detsisNo: '766', name: 'Zonguldak Valiliği', category: 'VALILIK' as const, city: 'Zonguldak' },
  { detsisNo: '767', name: 'Aksaray Valiliği', category: 'VALILIK' as const, city: 'Aksaray' },
  { detsisNo: '768', name: 'Bayburt Valiliği', category: 'VALILIK' as const, city: 'Bayburt' },
  { detsisNo: '769', name: 'Karaman Valiliği', category: 'VALILIK' as const, city: 'Karaman' },
  { detsisNo: '770', name: 'Kırıkkale Valiliği', category: 'VALILIK' as const, city: 'Kırıkkale' },
  { detsisNo: '771', name: 'Batman Valiliği', category: 'VALILIK' as const, city: 'Batman' },
  { detsisNo: '772', name: 'Şırnak Valiliği', category: 'VALILIK' as const, city: 'Şırnak' },
  { detsisNo: '773', name: 'Bartın Valiliği', category: 'VALILIK' as const, city: 'Bartın' },
  { detsisNo: '774', name: 'Ardahan Valiliği', category: 'VALILIK' as const, city: 'Ardahan' },
  { detsisNo: '775', name: 'Iğdır Valiliği', category: 'VALILIK' as const, city: 'Iğdır' },
  { detsisNo: '776', name: 'Yalova Valiliği', category: 'VALILIK' as const, city: 'Yalova' },
  { detsisNo: '777', name: 'Karabük Valiliği', category: 'VALILIK' as const, city: 'Karabük' },
  { detsisNo: '778', name: 'Kilis Valiliği', category: 'VALILIK' as const, city: 'Kilis' },
  { detsisNo: '779', name: 'Osmaniye Valiliği', category: 'VALILIK' as const, city: 'Osmaniye' },
  { detsisNo: '780', name: 'Düzce Valiliği', category: 'VALILIK' as const, city: 'Düzce' },
];
