export const MAX_CANONICAL_ENVELOPE_BYTES = 1_048_576;
export const MAX_BUCKET_COUNT = 10_000;
export const MAX_ATTRIBUTION_COUNT = 50_000;
export const MAX_CANONICAL_JSON_DEPTH = 32;

export const MAX_COMPONENT_CODE_CODE_POINTS = 128;
export const MAX_SOURCE_LINEAGE_SET_REF_CODE_POINTS = 512;
export const MAX_HISTORY_BOUNDARY_REF_CODE_POINTS = 512;
export const MAX_LEGAL_BASIS_REF_CODE_POINTS = 512;
export const MAX_EFFECTIVE_PERIOD_REF_CODE_POINTS = 256;
export const MAX_INTEREST_RULE_REF_CODE_POINTS = 256;
export const MAX_VERSION_IDENTIFIER_CODE_POINTS = 128;
export const MAX_CONTEXT_IDENTIFIER_CODE_POINTS = 256;

export const CANONICAL_SNAPSHOT_VALIDATION_REASONS = [
  'PAYLOAD_LIMIT_EXCEEDED',
  'BUCKET_LIMIT_EXCEEDED',
  'ATTRIBUTION_LIMIT_EXCEEDED',
  'STRING_LIMIT_EXCEEDED',
  'MAX_DEPTH_EXCEEDED',
  'DUPLICATE_JSON_MEMBER',
  'UNKNOWN_FIELD',
  'REQUIRED_FIELD_MISSING',
  'UNEXPECTED_NULL',
  'NON_NFC_STRING',
  'INVALID_INTEGER_STRING',
] as const;

export type CanonicalSnapshotValidationReason =
  (typeof CANONICAL_SNAPSHOT_VALIDATION_REASONS)[number];
