/**
 * Fee Engine Shared Types
 * 
 * TEK KAYNAK: Tüm masraf/tarife tanımları buradan import edilmeli
 * 
 * @see ARCHITECTURE.md - Source of Truth Matrix
 */

// ═══════════════════════════════════════════════════════════════════════════
// TARIFF TYPES - Tarife Tipleri
// ═══════════════════════════════════════════════════════════════════════════

export interface TariffFixedFee {
  amount: number;
  label: string;
  itemType: string;
  appliesTo: string[];
}

export interface TariffRateFee {
  rate: number;
  label: string;
  itemType: string;
  base: string;
  appliesTo: string[];
  minAmount?: number;
  maxAmount?: number;
}

export interface TariffPostage {
  amount: number | null;
  label: string;
  description: string;
  formula?: string;
}

export interface TariffInterestRate {
  startDate: string;
  rate: number;
}

export interface TariffPenalty {
  defaultRate: number;
  maxRate?: number;
  label: string;
}

export interface Tariff {
  version: number;
  year: number;
  effectiveDate: string;
  fixedFees: Record<string, TariffFixedFee>;
  rateFees: Record<string, TariffRateFee>;
  postage: Record<string, TariffPostage>;
  interestRates: Record<string, Record<string, TariffInterestRate[]>>;
  penalties: Record<string, TariffPenalty>;
}

// ═══════════════════════════════════════════════════════════════════════════
// FEE TYPES - Masraf Tipleri
// ═══════════════════════════════════════════════════════════════════════════

export enum FeeItemType {
  FEE = 'FEE',
  STAMP = 'STAMP',
  POSTAGE = 'POSTAGE',
  EXPENSE = 'EXPENSE',
  PENALTY = 'PENALTY',
}

export interface GeneratedFeeItem {
  type: FeeItemType | string;
  label: string;
  amount: number;
  currency: string;
  description?: string;
  isAutoGenerated: boolean;
  tariffCode?: string;
}

export interface FeeCalculationRequest {
  caseType: string;
  principalAmount: number;
  accruedInterest?: number;
  debtorCount?: number;
  postageType?: string;
  tariffYear?: number;
}

export interface FeeCalculationResult {
  items: GeneratedFeeItem[];
  totalAmount: number;
  tariffYear: number;
  calculatedAt: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// FEE PROFILE - Masraf Profili
// ═══════════════════════════════════════════════════════════════════════════

export interface FeeProfileItem {
  code: string;
  itemType: string;
  label: string;
  autoAdd: boolean;
  formula?: {
    base: string;
    rateFromTariff: string;
  };
}

export interface FeeProfile {
  appliesToCaseTypes: string[];
  tariffYear: number;
  fixedFeeItems: FeeProfileItem[];
  rateFeeItems: FeeProfileItem[];
  postagePolicy: {
    default: string;
    allow: string[];
    autoAdd: boolean;
    perDebtor?: boolean;
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// TARIFF REPOSITORY INTERFACE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Tarife okuma interface'i
 * 
 * fee-engine bu interface üzerinden tarife okur.
 * tariff modülü bu interface'i implement eder.
 */
export interface ITariffRepository {
  getTariff(year: number): Tariff | null;
  getActiveTariff(): Tariff | null;
  getAvailableYears(): number[];
}

// ═══════════════════════════════════════════════════════════════════════════
// GAZETTE NOTIFICATION
// ═══════════════════════════════════════════════════════════════════════════

export enum GazetteNotificationType {
  TARIFE = 'TARIFE',
  MEVZUAT = 'MEVZUAT',
  DIGER = 'DIGER',
}

export interface GazetteNotification {
  id: string;
  date: string;
  title: string;
  description: string;
  url: string;
  type: GazetteNotificationType;
  isRead: boolean;
  createdAt: Date;
}
