export default {
	ENFORCEMENT_REQUEST: {
		name: 'Takip Talebi',
		request: true,
		value: 'ENFORCEMENT_REQUEST',
	},
	21: {
		name: "21'e Göre Tebligat",
		request: true,
		warrant: false,
		envelope: true,
		value: 21,
	},
	35: {
		name: "35'E GÖRE TEBLİGAT",
		request: true,
		warrant: false,
		envelope: true,
		value: 35,
	},
	CLIENT_INTELLIGENCE: {
		name: 'MÜVEKKİL İSTİHBARATI',
		request: false,
		warrant: false,
		envelope: false,
		value: 'CLIENT_INTELLIGENCE',
	},
	FAMILY_REGISTER_INTELLIGENCE: {
		name: 'AİLE NUFÜS KAYDI (ANK)',
		request: true,
		warrant: false,
		envelope: false,
		value: 'FAMILY_REGISTER_INTELLIGENCE',
	},
	CIVIL_REGISTRY_INTELLIGENCE: {
		name: 'NÜFUS MÜDÜRLÜĞÜ İSTİHBARATI',
		request: true,
		warrant: false,
		envelope: false,
		value: 'CIVIL_REGISTRY_INTELLIGENCE',
	},
	CIVIL_REGISTRY_INTELLIGENCE_ALIAS: {
		name: 'NÜFUS MÜDÜRLÜĞÜ İSTİHBARATI TEKİD',
		request: true,
		warrant: false,
		envelope: false,
		value: 'CIVIL_REGISTRY_INTELLIGENCE_ALIAS',
	},
	SSI_INTELLIGENCE: {
		name: 'SGK İSTİHBARAT',
		request: true,
		warrant: false,
		envelope: false,
		value: 'SSI_INTELLIGENCE',
	},
	SSI_INTELLIGENCE_ALIAS: {
		name: 'SGK İSTİHBARAT TEKİD',
		request: true,
		warrant: false,
		envelope: false,
		value: 'SSI_INTELLIGENCE_ALIAS',
	},
	DE_FACTO_INTELLIGENCE: {
		name: 'FİİLİ ADRES İSTİHBARATI',
		request: false,
		warrant: false,
		envelope: false,
		value: 'DE_FACTO_INTELLIGENCE',
	},
	CHAMBER_OF_COMMERCE_INTELLIGENCE: {
		name: 'TİCARET ODASI İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'CHAMBER_OF_COMMERCE_INTELLIGENCE',
	},
	CHAMBER_OF_COMMERCE_INTELLIGENCE_ALIAS: {
		name: 'TİCARET ODASI İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'CHAMBER_OF_COMMERCE_INTELLIGENCE_ALIAS',
	},
	TAX_OFFICE_INTELLIGENCE: {
		name: 'VERGİ DAİRESİ İSTİHBARAT ',
		request: true,
		warrant: true,
		envelope: false,
		value: 'TAX_OFFICE_INTELLIGENCE',
	},
	TAX_OFFICE_INTELLIGENCE_ALIAS: {
		name: 'VERGİ DAİRESİ İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'TAX_OFFICE_INTELLIGENCE_ALIAS',
	},
	CUSTOMS_INTELLIGENCE: {
		name: 'GÜMRÜK MÜDÜRLÜĞÜ İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'CUSTOMS_INTELLIGENCE',
	},
	CUSTOMS_INTELLIGENCE_ALIAS: {
		name: 'GÜMRÜK MÜDÜRLÜĞÜ İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'CUSTOMS_INTELLIGENCE_ALIAS',
	},
	FAMILY_INTELLIGENCE: {
		name: 'AİLE BİREYLERİ İSTİHBARAT',
		request: true,
		warrant: false,
		envelope: false,
		value: 'FAMILY_INTELLIGENCE',
	},
	FAMILY_COMMERCIAL_INTELLIGENCE: {
		name: 'AİLE BİREYLERİ TİCARİ İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'FAMILY_COMMERCIAL_INTELLIGENCE',
	},
	GSM_INTELLIGENCE: {
		name: 'GSM İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'GSM_INTELLIGENCE',
	},
	GSM_INTELLIGENCE_ALIAS: {
		name: 'GSM İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'GSM_INTELLIGENCE_ALIAS',
	},
	COMAC_INTELLIGENCE: {
		name: 'ESNAF VE SANATKARLAR ODASI İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'COMAC_INTELLIGENCE',
	},
	COMAC_INTELLIGENCE_ALIAS: {
		name: 'ESNAF VE SANATKARLAR ODASI İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'COMAC_INTELLIGENCE_ALIAS',
	},
	POLICE_INTELLIGENCE: {
		name: 'KOLLUK KUVVETLERİ İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'POLICE_INTELLIGENCE',
	},
	POLICE_INTELLIGENCE_ALIAS: {
		name: 'KOLLUK KUVVETLERİ İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'POLICE_INTELLIGENCE_ALIAS',
	},
	MERNIS_INTELLIGENCE: {
		name: 'MERNİS İSTİHBARAT',
		request: true,
		warrant: true,
		envelope: false,
		value: 'MERNIS_INTELLIGENCE',
	},
	MERNIS_INTELLIGENCE_ALIAS: {
		name: 'MERNİS İSTİHBARAT TEKİD',
		request: true,
		warrant: true,
		envelope: false,
		value: 'MERNIS_INTELLIGENCE_ALIAS',
	},
	_89_1: {
		name: '89/1 Haciz Müzekkeresi',
		request: true,
		warrant: true,
		envelope: true,
	},
	WRIT_OF_EXECUTION: {
		name: 'İCRA EMRİ ',
		request: true,
		warrant: true,
		envelope: true,
	},
	TAX_OFFICE: {
		name: 'VERGİ DAİRESİ',
		request: true,
		warrant: true,
		envelope: false,
		value: 'TAX_OFFICE',
	},
	CUSTOMS: {
		name: 'GÜMRÜK MÜDÜRLÜĞÜ',
		request: true,
		warrant: true,
		envelope: false,
		value: 'CUSTOMS',
	},
	PATENT: {
		name: 'TÜRKİYE PATENT ENSTİTÜSÜ',
		request: true,
		warrant: true,
		envelope: false,
		value: 'PATENT',
	},
	CREDITOR_CASE: {
		name: 'ALACAKLI OLDUĞU DOSYA',
		request: true,
		warrant: true,
		envelope: false,
		value: 'CREDITOR_CASE',
	},
	SHARE_QUERY: {
		name: 'HİSSE SORGU',
		request: true,
		warrant: true,
		envelope: false,
		value: 'SHARE_QUERY',
	},
	SHARE_INPOUNDMENT: {
		name: 'HİSSE HACİZ',
		request: true,
		warrant: true,
		envelope: false,
		value: 'SHARE_INPOUNDMENT',
	},
	SHARE_NOTIFICATION: {
		name: 'TİCARET ODASI HACİZ TEBLİGATI',
		request: true,
		warrant: true,
		envelope: false,
		value: 'SHARE_NOTIFICATION',
	},
	BANK: {
		name: 'TOPLU BANKA',
		request: true,
		warrant: true,
		envelope: false,
		value: 'BANK',
	},
	VEHICLE_INPOUNDMENT: {
		name: 'ARAÇ HACİZ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'VEHICLE_INPOUNDMENT',
	},
	VEHICLE_WARRANT: {
		name: 'ARAÇ YAKALAMA',
		request: true,
		warrant: false,
		envelope: false,
		value: 'VEHICLE_WARRANT',
	},
	VEHICLE_SALE_ADVANCE: {
		name: 'ARAÇ SATIŞ AVANSI',
		request: true,
		warrant: false,
		envelope: false,
		value: 'VEHICLE_SALE_ADVANCE',
	},
	VEHICLE_103: {
		name: 'ARAÇ 103. MADDE',
		request: true,
		warrant: true,
		envelope: true,
		value: 'VEHICLE_103',
	},
	VEHICLE_100: {
		name: 'ARAÇ 100. MADDE',
		request: true,
		warrant: true,
		envelope: false,
		value: 'VEHICLE_100',
	},
	VEHICLE_APPRAISAL: {
		name: 'ARAÇ KIYMET TAKDİRİ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'VEHICLE_APPRAISAL',
	},
	VEHICLE_SALE_REQUEST: {
		name: 'ARAÇ SATIŞ TALEBİ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'VEHICLE_SALE_REQUEST',
	},
	IMMOVABLE_QUERY: {
		name: 'GAYRİMENKUL SORGU',
		request: true,
		warrant: false,
		envelope: false,
		value: 'IMMOVABLE_QUERY',
	},
	IMMOVABLE_INPOUNDMENT: {
		name: 'GAYRİMENKUL HACİZ',
		request: true,
		warrant: true,
		envelope: false,
		value: 'IMMOVABLE_INPOUNDMENT',
	},
	IMMOVABLE_SALE_ADVANCE: {
		name: 'GAYRİMENKUL SATIŞ AVANSI',
		request: true,
		warrant: false,
		envelope: false,
		value: 'IMMOVABLE_SALE_ADVANCE',
	},
	IMMOVABLE_103: {
		name: 'GAYRİMENKUL 103. MADDE',
		request: true,
		warrant: true,
		envelope: true,
		value: 'IMMOVABLE_103',
	},
	IMMOVABLE_100: {
		name: 'GAYRİMENKUL 100. MADDE',
		request: true,
		warrant: true,
		envelope: false,
		value: 'IMMOVABLE_100',
	},
	IMMOVABLE_ZONE: {
		name: 'GAYRİMENKUL ÇAP',
		request: true,
		warrant: true,
		envelope: false,
		value: 'IMMOVABLE_ZONE',
	},
	IMMOVABLE_CADASTRE: {
		name: 'GAYRİMENKUL İMAR',
		request: true,
		warrant: true,
		envelope: false,
		value: 'IMMOVABLE_CADASTRE',
	},
	IMMOVABLE_APPRAISAL: {
		name: 'GAYRİMENKUL KIYMET TAKDİRİ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'IMMOVABLE_APPRAISAL',
	},
	IMMOVABLE_SALE_REQUEST: {
		name: 'GAYRİMENKUL SATIŞ ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'IMMOVABLE_SALE_REQUEST',
	},
	COMMON_OWNERSHIP_121_REQUEST: {
		name: 'PAYLI MÜLKİYETTE 121 TALEBİ',
		request: true,
		warrant: false,
		envelope: false,
	},
	DECEASED_IMMOVABLE_QUERY: {
		name: 'GAYRİMENKUL MURİS SORGU',
		request: true,
		warrant: false,
		envelope: false,
	},
	DECEASED_IMMOVABLE_INPOUNDMENT: {
		name: 'GAYRİMENKUL MURİS HACİZ',
		request: true,
		warrant: true,
		envelope: false,
	},
	DECEASED_OWNERSHIP_121_QUERY: {
		name: "MURİS MÜLKİYETTE 121'E GÖRE SORGU",
		request: true,
		warrant: false,
		envelope: false,
	},
	DECEASED_IMMOVABLE_SALE_ADVANCE: {
		name: 'MURİS GAYRİMENKUL SATIŞ AVANSI ',
		request: true,
		warrant: false,
		envelope: false,
	},
	DECEASED_IMMOVABLE_103: {
		name: 'MURİS GAYRİMENKUL 103. MADDE',
		request: true,
		warrant: true,
		envelope: true,
	},
	DECEASED_IMMOVABLE_100: {
		name: 'MURİS GAYRİMENKUL 100. MADDE',
		request: true,
		warrant: false,
		envelope: false,
	},
	DECEASED_IMMOVABLE_ZONE: {
		name: 'MURİS GAYRİMENKUL ÇAP',
		request: true,
		warrant: true,
		envelope: false,
	},
	DECEASED_IMMOVABLE_CADASTRE: {
		name: 'MURİS GAYRİMENKUL İMAR',
		request: true,
		warrant: true,
		envelope: false,
	},
	DECEASED_IMMOVABLE_APPRAISAL: {
		name: 'MURİS GAYRİMENKUL KIYMET TAKDİRİ',
		request: true,
		warrant: false,
		envelope: false,
	},
	DECEASED_IMMOVABLE_SALE_REQUEST: {
		name: 'MURİS GAYRİMENKUL SATIŞ ',
		request: true,
		warrant: false,
		envelope: false,
	},
	SSI_QUERY: {
		name: 'SGK SORGU',
		request: true,
		warrant: false,
		envelope: false,
		value: 'SSI_QUERY',
	},
	GARNISHMENT: {
		name: 'MAAŞ HACZİ ',
		request: true,
		warrant: true,
		envelope: true,
		value: 'GARNISHMENT',
	},
	GARNISHMENT_CAHIER: {
		name: 'MAAŞ HACZİ MUHTIRA',
		request: true,
		warrant: true,
		envelope: true,
	},
	CALL_CENTER: {
		name: 'CALL CENTER',
		request: false,
		warrant: false,
		envelope: false,
	},
	COLLECTION_DECLARATION: {
		name: 'TAHSİLAT BEYANI',
		request: true,
		warrant: false,
		envelope: false,
		value: 'COLLECTION_DECLARATION',
	},
	DUE_REJECT_DECLARATION: {
		name: 'İSTİHKAK REDDİ BEYANI',
		request: true,
		warrant: false,
		envelope: false,
		value: 'DUE_REJECT_DECLARATION',
	},
	MOVABLE_INPOUNDMENT_BASE: {
		name: 'MENKUL HACZİ ESAS',
		request: true,
		warrant: false,
		envelope: false,
		value: 'MOVABLE_INPOUNDMENT_BASE',
	},
	MOVABLE_INPOUNDMENT_MANDATE: {
		name: 'MENKUL HACZİ TALİMAT',
		request: true,
		warrant: false,
		envelope: false,
		value: 'MOVABLE_INPOUNDMENT_MANDATE',
	},
	MOVABLE_SALE_ADVANCE: {
		name: 'MENKUL SATIŞ AVANSI',
		request: true,
		warrant: false,
		envelope: false,
		value: 'MOVABLE_SALE_ADVANCE',
	},
	MOVABLE_103: {
		name: 'MENKUL 103. MADDE',
		request: true,
		warrant: true,
		envelope: true,
		value: 'MOVABLE_103',
	},
	MOVABLE_100: {
		name: 'MENKUL 100. MADDE',
		request: true,
		warrant: true,
		envelope: false,
		value: 'MOVABLE_100',
	},
	MOVABLE_APPRAISAL: {
		name: 'MENKUL KIYMET TAKDİRİ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'MOVABLE_APPRAISAL',
	},
	MOVABLE_SALE_REQUEST: {
		name: 'MENKUL SATIŞ TALEBİ',
		request: true,
		warrant: false,
		envelope: false,
		value: 'MOVABLE_SALE_REQUEST',
	},
	MOVABLE_SALE_COMMITMENT: {
		name: 'TAAHHÜT',
		request: true,
		warrant: true,
		envelope: true,
		value: 'MOVABLE_SALE_COMMITMENT',
	},
	COMMITMENT_AGGRESSION: {
		name: 'TAAHHÜDÜ İHLAL DAVASI',
		request: false,
		warrant: true,
		envelope: false,
	},
	BAD_CHECK_CASE: {
		name: 'KARŞILIKSIZ ÇEK DAVASI',
		request: false,
		warrant: true,
		envelope: false,
	},
	GARNISHMENT_CRIMINAL_ACTION: {
		name: 'MAAŞ HACZİ CEZA DAVASI',
		request: false,
		warrant: true,
		envelope: false,
	},
	ABANDONMENT_OF_TRADE: {
		name: 'TİCARETİ BEYANSIZ TERK CEZA DAVASI ',
		request: false,
		warrant: true,
		envelope: false,
	},
	NOT_WANTING_BANKRUPTCY: {
		name: 'İFLAS İSTEMEME CEZA DAVASI',
		request: false,
		warrant: true,
		envelope: false,
	},
	CADASTRE_LIFT: {
		name: 'TAPU HACİZ FEK',
		request: true,
		warrant: true,
		envelope: false,
	},
	GARNISHMENT_LIFT: {
		name: 'MAAŞ HACZİ FEK',
		request: true,
		warrant: true,
		envelope: false,
	},
	COMMITMENT_AGGRESSION_LIFT: {
		name: 'TAAHHÜDÜ İHLAL FEK',
		request: false,
		warrant: true,
		envelope: false,
	},
	BANK_LIFT: {
		name: 'BANKA FEK',
		request: true,
		warrant: true,
		envelope: false,
	},
	WARRANT_LIFT: {
		name: 'YAKALAMA KALDIRMA',
		request: true,
		warrant: false,
		envelope: false,
	},
	BAD_CHECK_LIFT: {
		name: 'KARŞILIKSIZ ÇEK FEK',
		request: false,
		warrant: true,
		envelope: false,
	},
}
