export { StatsWidget } from "./stats-widget";
export { ActivityFeed } from "./activity-feed";
export { UpcomingEvents } from "./upcoming-events";
export { QuickSummary } from "./quick-summary";
export { RecentCases } from "./recent-cases";
export { FavoriteCases } from "./favorite-cases";
export { AdvancedStats } from "./advanced-stats";
export { ChartWidget, CaseStatusChart, MonthlyCollectionChart, CaseTrendChart } from "./chart-widget";
export { DraggableDashboard, DraggableGrid } from "./draggable-dashboard";
export { LawyerPerformanceDashboard } from "./lawyer-performance";
export { ClientDashboard } from "./client-dashboard";
export { StickyNotes } from "./sticky-notes";
export { ThemeCustomizer } from "./theme-customizer";
